/**
 * Pure helpers for the Harvest Evidence Report local browser
 * print/export-to-PDF flow.
 *
 * No DOM, no I/O, no fetch. Deterministic and null-safe. Used by the
 * export button to set document.title before window.print() so the
 * browser-suggested filename is sensible, and to compose safe scope /
 * generated-at labels for the print-only section.
 *
 * Safety: never includes plant_id, grow_id, tent_id, user_id, raw
 * payloads, sensor readings, or device tokens. Never recommends a
 * harvest action.
 */
import type { HarvestEvidenceReport } from "@/lib/harvestEvidenceReportViewModel";

export const HARVEST_EVIDENCE_REPORT_EXPORT_FOOTER =
  "Generated by Verdant — Plant memory. Sensor truth. Better decisions.";

function pad2(n: number): string {
  return n < 10 ? `0${n}` : String(n);
}

export function formatIsoDateOnly(d: Date): string {
  if (!(d instanceof Date) || !Number.isFinite(d.getTime())) return "unknown";
  return `${d.getUTCFullYear()}-${pad2(d.getUTCMonth() + 1)}-${pad2(
    d.getUTCDate(),
  )}`;
}

export function buildHarvestEvidenceReportExportFilename(
  now: Date = new Date(),
): string {
  return `verdant-harvest-evidence-report-${formatIsoDateOnly(now)}.pdf`;
}

export function buildHarvestEvidenceReportExportTitle(
  now: Date = new Date(),
): string {
  return `Verdant — Harvest Evidence Report — ${formatIsoDateOnly(now)}`;
}

export function buildHarvestEvidenceReportGeneratedAtLabel(
  now: Date = new Date(),
): string {
  if (!(now instanceof Date) || !Number.isFinite(now.getTime())) {
    return "unknown";
  }
  // Display as ISO without milliseconds; deterministic in tests.
  return now.toISOString().replace(/\.\d{3}Z$/, "Z");
}

/**
 * Returns a safe, name-only scope label for the print header.
 *
 * Never includes plant_id, grow_id, tent_id, or any other internal id.
 * Falls back to a generic label when names are missing.
 */
export function buildHarvestEvidenceReportScopeLabel(
  report: HarvestEvidenceReport | null | undefined,
): string {
  if (!report || !Array.isArray(report.plants) || report.plants.length === 0) {
    return "All plants in current view";
  }
  const names = report.plants
    .map((p) =>
      typeof p.plantName === "string" && p.plantName.trim().length > 0
        ? p.plantName.trim()
        : "Unnamed plant",
    )
    .filter((s, i, arr) => arr.indexOf(s) === i);
  if (names.length === 0) return "All plants in current view";
  if (names.length === 1) return names[0];
  if (names.length <= 4) return names.join(", ");
  return `${names.slice(0, 3).join(", ")} +${names.length - 3} more`;
}

export interface HarvestEvidenceReportExportMetadata {
  title: string;
  filename: string;
  generatedAtLabel: string;
  scopeLabel: string;
  footer: string;
}

export function buildHarvestEvidenceReportExportMetadata(
  report: HarvestEvidenceReport | null | undefined,
  now: Date = new Date(),
): HarvestEvidenceReportExportMetadata {
  return {
    title: buildHarvestEvidenceReportExportTitle(now),
    filename: buildHarvestEvidenceReportExportFilename(now),
    generatedAtLabel: buildHarvestEvidenceReportGeneratedAtLabel(now),
    scopeLabel: buildHarvestEvidenceReportScopeLabel(report),
    footer: HARVEST_EVIDENCE_REPORT_EXPORT_FOOTER,
  };
}
