/**
 * phenoExampleStrains
 *
 * Ten deterministic, demo-labeled example phenos spanning the full expression
 * spectrum a keeper-hunter cares about — loud gas, dessert, fruit, a
 * yield-monster, a frost bomb, a herm-flagged beauty, a runt, a balanced
 * hold, a divisive funk, and a purple pheno grown in a different tent. They are
 * meant to be MIXED AND MATCHED on the showcase so different expressions can be
 * read against one another.
 *
 * Pure demo data. No I/O, no randomness, no writes. Values are illustrative
 * grower observations — nothing here is a real measurement.
 */
import type { PhenoCandidateInput } from "@/lib/phenoComparisonViewModel";

const GROW = "Loud Hunt 2026";
const TENT = "Flower Tent 1";

export const PHENO_EXAMPLE_STRAINS: readonly PhenoCandidateInput[] = [
  {
    candidateId: "ex-gas-champion",
    candidateLabel: "GMO Gas #1",
    strain: "GMO",
    growLabel: GROW,
    tentLabel: TENT,
    plantLabel: "Plant 1",
    stage: "post_cure",
    requireEcPh: true,
    requirePpfd: true,
    photos: [{ id: "ex-gas-ph1", caption: "Frosty, dense, gassy (demo)" }],
    expression: {
      round: "post_cure",
      traits: [
        { key: "nose_loudness", value: 10, note: "Room-filling gas — the loudest of the run" },
        { key: "vigor", value: 4 },
        { key: "structure", value: 5 },
        { key: "bud_density", value: 5 },
        { key: "trichome_coverage", value: 5 },
        { key: "stretch", value: 2 },
        { key: "yield_impression", value: 3 },
      ],
      aromaDescriptors: ["gas", "fuel", "diesel", "funk", "earthy"],
      noseNote: "Savory garlic-gas, sticks to your fingers.",
      sex: "female",
      smokeTest: {
        flavorDescriptors: ["gas", "funk", "pepper"],
        smoothness: 4,
        effectDescriptors: ["heady", "sedative", "couchlock"],
        potencyImpression: 5,
        verdict: "Keeper. Loudest nose, hardest hit. Cures dark and greasy.",
        testedAt: "2026-06-10T00:00:00.000Z",
      },
      labResult: {
        thcPct: 28.4,
        totalCannabinoidsPct: 31.1,
        dominantTerpenes: [
          { name: "caryophyllene", pct: 0.9 },
          { name: "limonene", pct: 0.6 },
          { name: "myrcene", pct: 0.5 },
        ],
        source: "coa",
        testedAt: "2026-06-12T00:00:00.000Z",
      },
    },
  },
  {
    candidateId: "ex-dessert",
    candidateLabel: "Gelato Dessert #4",
    strain: "Gelato",
    growLabel: GROW,
    tentLabel: TENT,
    plantLabel: "Plant 4",
    stage: "post_cure",
    requireEcPh: true,
    requirePpfd: true,
    photos: [{ id: "ex-des-ph1", caption: "Purple-tipped, candy nose (demo)" }],
    expression: {
      round: "post_cure",
      traits: [
        { key: "nose_loudness", value: 7 },
        { key: "vigor", value: 4 },
        { key: "structure", value: 5 },
        { key: "bud_density", value: 5 },
        { key: "trichome_coverage", value: 4 },
        { key: "stretch", value: 3 },
        { key: "yield_impression", value: 4 },
      ],
      aromaDescriptors: ["candy", "cake", "cream", "vanilla", "sweet"],
      noseNote: "Sugary dessert nose, best bag appeal of the group.",
      sex: "female",
      smokeTest: {
        flavorDescriptors: ["cream", "vanilla", "berry"],
        smoothness: 5,
        effectDescriptors: ["euphoric", "relaxing", "body"],
        potencyImpression: 4,
        verdict: "Crowd-pleaser. Smoothest smoke, top shelf looks.",
        testedAt: "2026-06-10T00:00:00.000Z",
      },
      labResult: {
        thcPct: 25.1,
        dominantTerpenes: [
          { name: "limonene", pct: 0.8 },
          { name: "linalool", pct: 0.4 },
        ],
        source: "coa",
        testedAt: "2026-06-12T00:00:00.000Z",
      },
    },
  },
  {
    candidateId: "ex-fruit",
    candidateLabel: "Tropic Punch #2",
    strain: "Tropicanna",
    growLabel: GROW,
    tentLabel: TENT,
    plantLabel: "Plant 2",
    stage: "late_flower",
    requireEcPh: true,
    requirePpfd: true,
    expression: {
      round: "late_flower",
      traits: [
        { key: "nose_loudness", value: 6 },
        { key: "vigor", value: 5 },
        { key: "structure", value: 4 },
        { key: "bud_density", value: 3 },
        { key: "trichome_coverage", value: 3 },
        { key: "stretch", value: 4 },
        { key: "yield_impression", value: 4 },
      ],
      aromaDescriptors: ["tropical", "mango", "berry", "citrus", "sweet"],
      noseNote: "Juicy tropical fruit, most vigorous plant in the tent.",
      sex: "female",
      // No smoke test yet (still in flower) — should flag no_smoke_test.
    },
  },
  {
    candidateId: "ex-yield-monster",
    candidateLabel: "Big Bud Yielder #7",
    strain: "Big Bud",
    growLabel: "Commercial Run",
    tentLabel: "Flower Tent 3",
    plantLabel: "Plant 7",
    stage: "post_cure",
    requireEcPh: true,
    requirePpfd: true,
    expression: {
      round: "post_cure",
      traits: [
        { key: "nose_loudness", value: 3, note: "Quiet nose — not loud" },
        { key: "vigor", value: 5 },
        { key: "structure", value: 3 },
        { key: "bud_density", value: 3 },
        { key: "trichome_coverage", value: 3 },
        { key: "stretch", value: 5 },
        { key: "yield_impression", value: 5, note: "Biggest yield by far" },
      ],
      aromaDescriptors: ["earthy", "herbal", "pine"],
      noseNote: "Commercially heavy but the nose just isn't loud.",
      sex: "female",
      smokeTest: {
        flavorDescriptors: ["earthy", "herbal"],
        smoothness: 3,
        effectDescriptors: ["functional", "relaxing"],
        potencyImpression: 3,
        verdict: "Great numbers, forgettable smoke. Pass for a keeper hunt.",
        testedAt: "2026-06-10T00:00:00.000Z",
      },
    },
  },
  {
    candidateId: "ex-frost-bomb",
    candidateLabel: "White Frost #3",
    strain: "White Runtz",
    growLabel: GROW,
    tentLabel: TENT,
    plantLabel: "Plant 3",
    stage: "late_flower",
    requireEcPh: true,
    requirePpfd: true,
    photos: [{ id: "ex-frost-ph1", caption: "Total resin coverage (demo)" }],
    expression: {
      round: "late_flower",
      traits: [
        { key: "nose_loudness", value: 5 },
        { key: "vigor", value: 2, note: "Slow, sulky in veg" },
        { key: "structure", value: 4 },
        { key: "bud_density", value: 5 },
        { key: "trichome_coverage", value: 5, note: "Whitest, frostiest plant" },
        { key: "stretch", value: 2 },
        { key: "yield_impression", value: 3 },
      ],
      aromaDescriptors: ["gas", "mint", "cream", "pine"],
      noseNote: "Menthol-gas over cream. Insane frost, weak vigor.",
      sex: "female",
    },
  },
  {
    candidateId: "ex-herm-prone",
    candidateLabel: "Cherry Pheno #9",
    strain: "Cherry Punch",
    growLabel: GROW,
    tentLabel: TENT,
    plantLabel: "Plant 9",
    stage: "late_flower",
    requireEcPh: true,
    requirePpfd: true,
    expression: {
      round: "late_flower",
      traits: [
        { key: "nose_loudness", value: 8 },
        { key: "vigor", value: 4 },
        { key: "structure", value: 5 },
        { key: "bud_density", value: 4 },
        { key: "trichome_coverage", value: 4 },
        { key: "stretch", value: 3 },
        { key: "yield_impression", value: 4 },
      ],
      aromaDescriptors: ["berry", "candy", "sweet", "sour", "gas"],
      noseNote: "Gorgeous loud cherry-gas — heartbreaker.",
      sex: "hermaphrodite",
      hermObserved: true,
      hermNote: "Nanners at the base of two colas, week 6. Whole clonal line is suspect.",
    },
  },
  {
    candidateId: "ex-runt",
    candidateLabel: "Runt #11",
    strain: "Zkittlez",
    growLabel: GROW,
    tentLabel: TENT,
    plantLabel: "Plant 11",
    stage: "mid_flower",
    requireEcPh: true,
    requirePpfd: true,
    expression: {
      round: "mid_flower",
      traits: [
        { key: "nose_loudness", value: 5 },
        { key: "vigor", value: 1, note: "Never took off — half the size of siblings" },
        { key: "structure", value: 3 },
        { key: "bud_density", value: 3 },
        { key: "trichome_coverage", value: 3 },
        { key: "stretch", value: 1 },
        { key: "yield_impression", value: 1 },
      ],
      aromaDescriptors: ["funk", "sour", "candy"],
      noseNote: "Nose is decent but the plant is a runt — not worth the space.",
      sex: "female",
    },
  },
  {
    candidateId: "ex-balanced",
    candidateLabel: "All-Rounder #5",
    strain: "Wedding Cake",
    growLabel: GROW,
    tentLabel: TENT,
    plantLabel: "Plant 5",
    stage: "post_cure",
    requireEcPh: true,
    requirePpfd: true,
    expression: {
      round: "post_cure",
      traits: [
        { key: "nose_loudness", value: 5 },
        { key: "vigor", value: 4 },
        { key: "structure", value: 4 },
        { key: "bud_density", value: 4 },
        { key: "trichome_coverage", value: 4 },
        { key: "stretch", value: 3 },
        { key: "yield_impression", value: 4 },
      ],
      aromaDescriptors: ["earthy", "sweet", "gas", "vanilla"],
      noseNote: "Solid everywhere, standout nowhere. Classic hold.",
      sex: "female",
      smokeTest: {
        flavorDescriptors: ["earthy", "vanilla"],
        smoothness: 4,
        effectDescriptors: ["relaxing", "functional"],
        potencyImpression: 4,
        verdict: "Nothing wrong with it, nothing special. Hold and re-run.",
        testedAt: "2026-06-10T00:00:00.000Z",
      },
    },
  },
  {
    candidateId: "ex-funk-cheese",
    candidateLabel: "Funk Bomb #6",
    strain: "UK Cheese",
    growLabel: GROW,
    tentLabel: TENT,
    plantLabel: "Plant 6",
    stage: "post_cure",
    requireEcPh: true,
    requirePpfd: true,
    expression: {
      round: "post_cure",
      traits: [
        { key: "nose_loudness", value: 9 },
        { key: "vigor", value: 4 },
        { key: "structure", value: 4 },
        { key: "bud_density", value: 5 },
        { key: "trichome_coverage", value: 3 },
        { key: "stretch", value: 3 },
        { key: "yield_impression", value: 4 },
      ],
      aromaDescriptors: ["cheese", "skunk", "funk", "sour"],
      noseNote: "Rank pungent cheese-funk. Divisive — you love it or you don't.",
      sex: "female",
      smokeTest: {
        flavorDescriptors: ["cheese", "funk", "sour"],
        smoothness: 3,
        effectDescriptors: ["relaxing", "giggly"],
        potencyImpression: 4,
        verdict: "Loud and unique. Niche keeper for the funk crowd.",
        testedAt: "2026-06-10T00:00:00.000Z",
      },
    },
  },
  {
    candidateId: "ex-purple",
    candidateLabel: "Purple Haze Pheno #8",
    strain: "Purple Haze",
    growLabel: GROW,
    tentLabel: "Flower Tent 2",
    plantLabel: "Plant 8",
    stage: "late_flower",
    requireEcPh: true,
    requirePpfd: true,
    photos: [{ id: "ex-purple-ph1", caption: "Deep lavender-purple bud (demo)" }],
    expression: {
      round: "late_flower",
      traits: [
        { key: "nose_loudness", value: 6 },
        { key: "vigor", value: 4 },
        { key: "structure", value: 4 },
        { key: "bud_density", value: 3 },
        { key: "trichome_coverage", value: 4 },
        { key: "stretch", value: 4 },
        { key: "yield_impression", value: 3 },
      ],
      aromaDescriptors: ["grape", "floral", "lavender", "berry", "sweet"],
      noseNote: "Grape-floral, turns deep purple in the cold. Best color of the run.",
      sex: "female",
    },
  },
];

/** A curated default subset that shows off the expression range on first load. */
export const PHENO_SHOWCASE_DEFAULT_SELECTION: readonly string[] = [
  "ex-gas-champion",
  "ex-dessert",
  "ex-fruit",
  "ex-herm-prone",
];
