/**
 * MCP manifest drift test.
 *
 * The Agent Integrations page reads presenter-safe metadata from
 * `src/lib/mcp/manifestView.ts` (a typed TS constant). The real source
 * of truth is `.lovable/mcp/manifest.json`, which is regenerated by the
 * mcp-js Vite plugin.
 *
 * This test reads the real manifest at test time and asserts the TS
 * view matches the tool names, required/optional parameter surface,
 * server identity, and OAuth issuer shape. If the manifest changes and
 * this constant drifts, this test fails loudly instead of silently
 * showing stale docs on the settings page.
 */
import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { MCP_MANIFEST } from "@/lib/mcp/manifestView";

type RawTool = {
  name: string;
  title: string;
  description: string;
  annotations?: { readOnlyHint?: boolean };
  inputSchema?: {
    properties?: Record<string, unknown>;
    required?: string[];
  };
};

function loadRealManifest() {
  const path = resolve(process.cwd(), ".lovable/mcp/manifest.json");
  const raw = readFileSync(path, "utf8");
  return JSON.parse(raw) as {
    path: string;
    auth: { type: string; issuer: string; accepted_audiences?: string[] };
    mcp: {
      server: { name: string; title: string; version: string };
      tools: RawTool[];
    };
    sdk_version?: string;
  };
}

describe("MCP manifest drift", () => {
  const real = loadRealManifest();

  it("server identity mirrors the real manifest", () => {
    expect(MCP_MANIFEST.serverName).toBe(real.mcp.server.name);
    expect(MCP_MANIFEST.serverTitle).toBe(real.mcp.server.title);
    expect(MCP_MANIFEST.version).toBe(real.mcp.server.version);
    expect(MCP_MANIFEST.path).toBe(real.path);
    if (real.sdk_version) {
      expect(MCP_MANIFEST.sdkVersion).toBe(real.sdk_version);
    }
  });

  it("OAuth issuer is the direct supabase.co host, not a proxy", () => {
    expect(real.auth.type).toBe("oauth");
    expect(MCP_MANIFEST.oauthIssuer).toBe(real.auth.issuer);
    expect(MCP_MANIFEST.oauthIssuer).toMatch(
      /^https:\/\/[a-z0-9-]+\.supabase\.co\/auth\/v1$/,
    );
    expect(MCP_MANIFEST.oauthIssuer).not.toMatch(/lovable\.cloud/);
  });

  it("exposes exactly the three read-only tools", () => {
    const realNames = real.mcp.tools.map((t) => t.name).sort();
    const viewNames = MCP_MANIFEST.tools.map((t) => t.name).sort();
    expect(viewNames).toEqual(realNames);
    expect(viewNames).toEqual(
      [
        "get_latest_sensor_snapshot",
        "list_grows",
        "list_recent_diary_entries",
      ].sort(),
    );
  });

  it("every tool is annotated read-only in the real manifest", () => {
    for (const tool of real.mcp.tools) {
      expect(tool.annotations?.readOnlyHint).toBe(true);
    }
    for (const tool of MCP_MANIFEST.tools) {
      expect(tool.readOnly).toBe(true);
    }
  });

  it("required vs optional parameter surface matches", () => {
    for (const realTool of real.mcp.tools) {
      const view = MCP_MANIFEST.tools.find((t) => t.name === realTool.name);
      expect(view, `view missing for ${realTool.name}`).toBeDefined();

      const realProps = Object.keys(realTool.inputSchema?.properties ?? {}).sort();
      const viewProps = view!.params.map((p) => p.name).sort();
      expect(viewProps).toEqual(realProps);

      const realRequired = new Set(realTool.inputSchema?.required ?? []);
      for (const p of view!.params) {
        expect(p.required).toBe(realRequired.has(p.name));
      }
    }
  });
});
