import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";
import {
  hashLooksLikeOAuthReturn,
  OAUTH_HASH_EARLY_WIPE_SCRIPT,
  parseOAuthHashFragment,
} from "@/lib/oauthHashSessionConsumeRules";

const ROOT = resolve(__dirname, "../..");

function read(rel: string): string {
  return readFileSync(resolve(ROOT, rel), "utf8");
}

describe("oauth hash session consume wiring", () => {
  it("AuthProvider consumes OAuth hash before getSession via the rules helper", () => {
    const authSrc = read("src/store/auth.tsx");
    expect(authSrc).toContain("consumeOAuthHashSessionIfPresent");
    expect(authSrc).toContain("takeOAuthReturnHashStash");
    expect(authSrc).toContain("stashedHash");
    expect(authSrc).toContain("supabase.auth.setSession");
    expect(authSrc).toContain("history.replaceState");
    expect(authSrc).not.toMatch(/console\.(log|debug|info|warn|error)\(/);

    // Bootstrap IIFE: hash consume completes before the initial getSession.
    // (reconcileWithClientSession also calls getSession earlier in the file.)
    expect(authSrc).toMatch(
      /await consumeOAuthHashSessionIfPresent\(\{[\s\S]*?\}\);[\s\S]*?if \(disposed\) return;[\s\S]*?await supabase\.auth\.getSession\(\)/,
    );
  });

  it("early wipe script matches parseOAuthHashFragment keys (resolved constant)", () => {
    expect(OAUTH_HASH_EARLY_WIPE_SCRIPT).toContain("URLSearchParams");
    expect(OAUTH_HASH_EARLY_WIPE_SCRIPT).toContain('p.has("access_token")');
    expect(OAUTH_HASH_EARLY_WIPE_SCRIPT).toContain('p.has("refresh_token")');
    expect(OAUTH_HASH_EARLY_WIPE_SCRIPT).toContain('p.has("error")');
    expect(OAUTH_HASH_EARLY_WIPE_SCRIPT).not.toContain('indexOf("access_token=")');
    expect(OAUTH_HASH_EARLY_WIPE_SCRIPT).not.toMatch(/console\./);
    expect(parseOAuthHashFragment("#myaccess_token=1")).toEqual({ kind: "none" });
    expect(parseOAuthHashFragment("#section?error=1")).toEqual({ kind: "none" });
    expect(hashLooksLikeOAuthReturn("#myaccess_token=1")).toBe(false);
    expect(hashLooksLikeOAuthReturn("#section?error=1")).toBe(false);
  });

  it("root document inlines the early wipe script in head before HeadContent", () => {
    const rootSrc = read("src/routes/__root.tsx");
    expect(rootSrc).toContain("OAUTH_HASH_EARLY_WIPE_SCRIPT");
    expect(rootSrc).toMatch(
      /<head>\s*<script[\s\S]*?dangerouslySetInnerHTML=\{\{\s*__html:\s*OAUTH_HASH_EARLY_WIPE_SCRIPT\s*\}\}[\s\S]*?\/>\s*<HeadContent \/>/,
    );
    expect(rootSrc).not.toMatch(/console\.(log|debug|info)\(/);
  });

  it("ResetPassword diagnoses from the before-paint stash, not a wiped location.hash", () => {
    const resetSrc = read("src/pages/ResetPassword.tsx");
    expect(resetSrc).toContain("peekOAuthReturnHashStash");
    expect(resetSrc).toContain("capturedHashRef");
    expect(resetSrc).toContain("shouldAttemptOAuthHashSessionConsume");
    expect(resetSrc).toContain("diagnoseResetLink");
  });

  it("does not rely on editing the auto-generated Lovable OAuth shim or supabase client", () => {
    const lovableSrc = read("src/integrations/lovable/index.ts");
    expect(lovableSrc).toContain("auto-generated by Lovable");
    // Stay out of the generated shim for return-hash consume.
    expect(lovableSrc).not.toContain("oauthHashSessionConsumeRules");

    const clientSrc = read("src/integrations/supabase/client.ts");
    expect(clientSrc).not.toContain("detectSessionInUrl");
    expect(clientSrc).not.toContain("flowType");
    expect(clientSrc).not.toContain("oauthHashSessionConsumeRules");
  });
});
