import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

const ROOT = resolve(__dirname, "../..");

describe("oauth hash session consume wiring", () => {
  it("AuthProvider consumes OAuth hash before getSession via the rules helper", () => {
    const authSrc = readFileSync(resolve(ROOT, "src/store/auth.tsx"), "utf8");
    expect(authSrc).toContain(
      'import { consumeOAuthHashSessionIfPresent } from "@/lib/oauthHashSessionConsumeRules"',
    );
    expect(authSrc).toContain("consumeOAuthHashSessionIfPresent");
    expect(authSrc).toContain("supabase.auth.setSession");
    expect(authSrc).toContain("history.replaceState");

    // Bootstrap IIFE: hash consume completes before the initial getSession.
    // (reconcileWithClientSession also calls getSession earlier in the file.)
    expect(authSrc).toMatch(
      /await consumeOAuthHashSessionIfPresent\(\{[\s\S]*?\}\);[\s\S]*?if \(disposed\) return;[\s\S]*?await supabase\.auth\.getSession\(\)/,
    );
  });

  it("does not rely on editing the auto-generated Lovable OAuth shim or supabase client", () => {
    const lovableSrc = readFileSync(
      resolve(ROOT, "src/integrations/lovable/index.ts"),
      "utf8",
    );
    expect(lovableSrc).toContain("auto-generated by Lovable");
    // Stay out of the generated shim for return-hash consume.
    expect(lovableSrc).not.toContain("oauthHashSessionConsumeRules");

    const clientSrc = readFileSync(
      resolve(ROOT, "src/integrations/supabase/client.ts"),
      "utf8",
    );
    expect(clientSrc).not.toContain("detectSessionInUrl");
    expect(clientSrc).not.toContain("oauthHashSessionConsumeRules");
  });
});
