import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

const ROOT = resolve(__dirname, "../..");

function read(rel: string): string {
  return readFileSync(resolve(ROOT, rel), "utf8");
}

describe("oauth hash session consume wiring", () => {
  it("AuthProvider consumes OAuth hash before getSession via the rules helper", () => {
    const authSrc = read("src/store/auth.tsx");
    expect(authSrc).toContain("consumeOAuthHashSessionIfPresent");
    expect(authSrc).toContain("takeOAuthReturnHashStash");
    expect(authSrc).toContain("stashedHash");
    expect(authSrc).toContain("supabase.auth.setSession");
    expect(authSrc).toContain("history.replaceState");
    expect(authSrc).not.toMatch(/console\.(log|debug|info|warn|error)\(/);

    // Bootstrap IIFE: hash consume completes before the initial getSession.
    // (reconcileWithClientSession also calls getSession earlier in the file.)
    expect(authSrc).toMatch(
      /await consumeOAuthHashSessionIfPresent\(\{[\s\S]*?\}\);[\s\S]*?if \(disposed\) return;[\s\S]*?await supabase\.auth\.getSession\(\)/,
    );
  });

  it("consume wipes via replaceState before awaiting setSession", () => {
    const rulesSrc = read("src/lib/oauthHashSessionConsumeRules.ts");
    const consumeStart = rulesSrc.indexOf("export async function consumeOAuthHashSessionIfPresent");
    expect(consumeStart).toBeGreaterThanOrEqual(0);
    const consumeSrc = rulesSrc.slice(consumeStart);
    const wipeAt = consumeSrc.indexOf("clearOAuthHashFromAddressBar");
    const setSessionAt = consumeSrc.indexOf("await deps.setSession");
    expect(wipeAt).toBeGreaterThan(0);
    expect(setSessionAt).toBeGreaterThan(wipeAt);
    expect(rulesSrc).not.toMatch(/console\.(log|debug|info|warn|error)\(/);
  });

  it("root document runs the early wipe script as the first head child", () => {
    const rootSrc = read("src/routes/__root.tsx");
    expect(rootSrc).toContain("OAUTH_HASH_EARLY_WIPE_SCRIPT");
    expect(rootSrc).toMatch(
      /<head>\s*<script[\s\S]*?dangerouslySetInnerHTML=\{\{\s*__html:\s*OAUTH_HASH_EARLY_WIPE_SCRIPT\s*\}\}[\s\S]*?\/>\s*<HeadContent \/>/,
    );
    expect(rootSrc).not.toMatch(/console\.(log|debug|info)\(/);
  });

  it("does not rely on editing the auto-generated Lovable OAuth shim or supabase client", () => {
    const lovableSrc = read("src/integrations/lovable/index.ts");
    expect(lovableSrc).toContain("auto-generated by Lovable");
    // Stay out of the generated shim for return-hash consume.
    expect(lovableSrc).not.toContain("oauthHashSessionConsumeRules");

    const clientSrc = read("src/integrations/supabase/client.ts");
    expect(clientSrc).not.toContain("detectSessionInUrl");
    expect(clientSrc).not.toContain("flowType");
    expect(clientSrc).not.toContain("oauthHashSessionConsumeRules");
  });
});
