/**
 * Prettier fence for the Sentinel governance mirror.
 *
 * GEMINI.md embeds the whole of AGENTS.md verbatim inside its
 * <!-- SENTINEL-CORE:BEGIN ... END --> block, and the MIRROR half of
 * scripts/check-sentinel-version-parity.mjs requires the two to stay
 * byte-equivalent (modulo line endings and Sentinel-Version lines).
 *
 * Prettier formats the same bytes differently in the two files — inside
 * GEMINI.md it de-indents a continuation block it leaves alone in AGENTS.md,
 * because the enclosing list context differs. So formatting EITHER file
 * desynchronises the mirror. Reproduced before this fence existed:
 * `npx prettier --write GEMINI.md` made the checker report
 * "GEMINI.md: embedded SENTINEL-CORE differs from AGENTS.md".
 *
 * That is not hypothetical. .husky/pre-commit runs `npx lint-staged`, whose
 * "*.{...,md,...}" rule runs `prettier --write` — a write, not a check — and a
 * slash-free lint-staged glob matches on basename, so root-level AGENTS.md and
 * GEMINI.md both hit it. Without the .prettierignore entries a contributor with
 * the hook installed silently corrupts the mirror on commit.
 *
 * Both files are regenerated by scripts/sync-sentinel-mirror.mjs. Neither is
 * ever formatted by hand or by a formatter.
 *
 * The first two cases assert the RESOLVED ignore decision via Prettier's own
 * getFileInfo rather than scanning .prettierignore as text, so they still hold
 * if the entries are reordered, if a path is rewritten, or if a later negation
 * pattern (!GEMINI.md) silently undoes the fence.
 */
import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { join, resolve } from "node:path";

const ROOT = resolve(__dirname, "..", "..");
const IGNORE_PATH = join(ROOT, ".prettierignore");

/** Mirrors CORE_BEGIN / CORE_END in scripts/check-sentinel-version-parity.mjs. */
const CORE_BEGIN = "<!-- SENTINEL-CORE:BEGIN";
const CORE_END = "<!-- SENTINEL-CORE:END";

/** Mirrors VERSION_RE in scripts/check-sentinel-version-parity.mjs. */
const VERSION_RE = /Sentinel-Version:\s*([0-9]{4}-[0-9]{2}-[0-9]{2}\.[0-9]+)/;

/** Mirrors normalize() in scripts/check-sentinel-version-parity.mjs. */
function normalize(text: string): string {
  return text
    .replace(/\r\n/g, "\n")
    .split("\n")
    .filter((line) => !VERSION_RE.test(line))
    .join("\n")
    .trim();
}

/** Mirrors embeddedGeminiCore() in scripts/check-sentinel-version-parity.mjs. */
function embeddedGeminiCore(text: string): string | null {
  const begin = text.indexOf(CORE_BEGIN);
  const end = text.indexOf(CORE_END);
  if (begin === -1 || end === -1 || end <= begin) return null;

  const beginLineEnd = text.indexOf("\n", begin);
  if (beginLineEnd === -1 || beginLineEnd >= end) return null;

  return text.slice(beginLineEnd + 1, end).trim();
}

async function isPrettierIgnored(relativePath: string): Promise<boolean> {
  const prettier = await import("prettier");
  const info = await prettier.getFileInfo(join(ROOT, relativePath), {
    ignorePath: IGNORE_PATH,
  });
  return info.ignored;
}

describe("sentinel mirror prettier fence", () => {
  it("resolves AGENTS.md as Prettier-ignored", async () => {
    await expect(isPrettierIgnored("AGENTS.md")).resolves.toBe(true);
  });

  it("resolves GEMINI.md as Prettier-ignored", async () => {
    await expect(isPrettierIgnored("GEMINI.md")).resolves.toBe(true);
  });

  it("does not over-fence — CLAUDE.md stays Prettier-formatted", async () => {
    // CLAUDE.md is not mirrored; the checker only tests its three-line import
    // prefix and its version line. Formatting it is harmless, so it must not be
    // swept into the fence.
    await expect(isPrettierIgnored("CLAUDE.md")).resolves.toBe(false);
  });

  it("keeps GEMINI.md's SENTINEL-CORE byte-equivalent to AGENTS.md", () => {
    // The same invariant the MIRROR check enforces. It lives here as well
    // because sentinel-version-parity.yml is path-filtered and is NOT one of
    // the required contexts in config/required-status-checks.json, whereas the
    // Vitest shards are.
    const agents = readFileSync(join(ROOT, "AGENTS.md"), "utf8");
    const gemini = readFileSync(join(ROOT, "GEMINI.md"), "utf8");

    const core = embeddedGeminiCore(gemini);
    expect(core, "GEMINI.md is missing its SENTINEL-CORE block").not.toBeNull();
    expect(
      normalize(core as string),
      "GEMINI.md's embedded SENTINEL-CORE differs from AGENTS.md — regenerate it with " +
        "`node scripts/sync-sentinel-mirror.mjs`, do not hand-edit GEMINI.md",
    ).toBe(normalize(agents));
  });
});
