import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";
import type { ConfigEnv, UserConfig } from "vite";

const root = process.cwd();
const viteConfigSource = readFileSync(resolve(root, "vite.config.ts"), "utf8");
const generatedMcpFunction = readFileSync(resolve(root, "supabase/functions/mcp/index.ts"), "utf8");
const packageJson = JSON.parse(readFileSync(resolve(root, "package.json"), "utf8")) as {
  scripts?: Record<string, string>;
};

type ViteConfigExport =
  | UserConfig
  | Promise<UserConfig>
  | ((env: ConfigEnv) => UserConfig | Promise<UserConfig>);

function flattenPlugins(plugins: unknown): Array<{ name?: string }> {
  if (!Array.isArray(plugins)) return [];
  const out: Array<{ name?: string }> = [];
  for (const plugin of plugins) {
    if (!plugin) continue;
    if (Array.isArray(plugin)) {
      out.push(...flattenPlugins(plugin));
      continue;
    }
    if (typeof plugin === "object" && plugin !== null && !("then" in plugin)) {
      out.push(plugin as { name?: string });
    }
  }
  return out;
}

describe("Lovable MCP codegen host safety", () => {
  it("does not invoke mcpPlugin from vite.config (Linux/Lovable/CI must not rewrite the MCP bundle)", async () => {
    // Prior contract gated codegen with `process.platform !== "win32" && mcpPlugin()`.
    // That still regenerated `supabase/functions/mcp/index.ts` on every non-Windows
    // vite dev/build. The plugin must not be wired at all.
    const codeWithoutLineComments = viteConfigSource
      .split("\n")
      .map((line) => line.replace(/\/\/.*$/, ""))
      .join("\n");
    expect(codeWithoutLineComments).not.toMatch(/\bmcpPlugin\s*\(/);
    expect(codeWithoutLineComments).not.toMatch(/@lovable\.dev\/mcp-js/);
    expect(codeWithoutLineComments).not.toMatch(/\bfrom\s+["'][^"']*mcp-js[^"']*["']/);

    const mod = await import("../../vite.config");
    const exported = mod.default as ViteConfigExport;
    const env: ConfigEnv = { command: "serve", mode: "development", isSsrBuild: false };
    const resolved = await Promise.resolve(typeof exported === "function" ? exported(env) : exported);
    const pluginNames = flattenPlugins(resolved.plugins).map((plugin) => plugin.name ?? "");

    expect(pluginNames.some((name) => /mcp/i.test(name))).toBe(false);
  });

  it("keeps the checked-in Supabase MCP function portable", () => {
    expect(generatedMcpFunction).not.toMatch(/(?:npm:)?[A-Za-z]:[\\/].*src[\\/]lib[\\/]mcp/);
    expect(generatedMcpFunction).not.toMatch(/(?:from\s+|import\s*)["'](?:npm:)?@\//);
    expect(generatedMcpFunction).toContain("AUTO-GENERATED by @lovable.dev/mcp-js");
  });

  it("checks Edge import portability before and after production builds", () => {
    expect(packageJson.scripts?.prebuild).toContain("check-no-src-lib-imports.mjs");
    // postbuild routes through run-postbuild-seo, which runs the same scanner.
    expect(packageJson.scripts?.postbuild).toContain("run-postbuild-seo.mjs");
    const postbuildRunner = readFileSync(resolve(root, "scripts/run-postbuild-seo.mjs"), "utf8");
    expect(postbuildRunner).toContain("check-no-src-lib-imports.mjs");
  });
});
