import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

const root = process.cwd();
const viteConfig = readFileSync(resolve(root, "vite.config.ts"), "utf8");
const generatedMcpFunction = readFileSync(resolve(root, "supabase/functions/mcp/index.ts"), "utf8");
const packageJson = JSON.parse(readFileSync(resolve(root, "package.json"), "utf8")) as {
  scripts?: Record<string, string>;
};

describe("Lovable MCP codegen host safety", () => {
  it("does not run the known-broken MCP codegen path on Windows", () => {
    expect(viteConfig).toMatch(/process\.platform\s*!==\s*["']win32["']\s*&&\s*mcpPlugin\(\)/);
  });

  it("keeps the checked-in Supabase MCP function portable", () => {
    expect(generatedMcpFunction).not.toMatch(/(?:npm:)?[A-Za-z]:[\\/].*src[\\/]lib[\\/]mcp/);
    expect(generatedMcpFunction).not.toMatch(/(?:from\s+|import\s*)["'](?:npm:)?@\//);
    expect(generatedMcpFunction).toContain("AUTO-GENERATED by @lovable.dev/mcp-js");
  });

  it("checks Edge import portability before and after production builds", () => {
    expect(packageJson.scripts?.prebuild).toContain("check-no-src-lib-imports.mjs");
    // postbuild routes through run-postbuild-seo, which runs the same scanner.
    expect(packageJson.scripts?.postbuild).toContain("run-postbuild-seo.mjs");
    const postbuildRunner = readFileSync(resolve(root, "scripts/run-postbuild-seo.mjs"), "utf8");
    expect(postbuildRunner).toContain("check-no-src-lib-imports.mjs");
  });
});
