/**
 * Edge Function shared subset of `src/lib/vpdRules.ts`.
 *
 * Only the symbols the EcoWitt routed-row builder needs at runtime live
 * here. The full set (with extra exports used by the React app) remains in
 * `src/lib/vpdRules.ts`. Keep behavior identical — drift here would let
 * the deployed edge function compute VPD differently from app code.
 *
 * Do NOT edit this file without updating `src/lib/vpdRules.ts` to match.
 */

export const AIR_TEMP_MIN_C = -20;
export const AIR_TEMP_MAX_C = 60;

export function fahrenheitToCelsius(f: number): number {
  return ((f - 32) * 5) / 9;
}

function isFiniteNumber(v: unknown): v is number {
  return typeof v === "number" && Number.isFinite(v);
}

export interface CalculateAirVpdInput {
  tempC?: number | null;
  tempF?: number | null;
  tempUnit?: "C" | "F";
  rhPercent: number | null | undefined;
}

export function calculateAirVpdKpa(
  input: CalculateAirVpdInput,
): number | null {
  if (!input) return null;
  const { rhPercent } = input;

  let tempC: number | null = null;
  if (isFiniteNumber(input.tempC)) {
    tempC = input.tempC;
  } else if (isFiniteNumber(input.tempF)) {
    tempC = fahrenheitToCelsius(input.tempF);
  }

  if (!isFiniteNumber(tempC)) return null;
  if (tempC < AIR_TEMP_MIN_C || tempC > AIR_TEMP_MAX_C) return null;

  if (!isFiniteNumber(rhPercent)) return null;
  if (rhPercent < 0 || rhPercent > 100) return null;

  const es = 0.6108 * Math.exp((17.27 * tempC) / (tempC + 237.3));
  const vpd = es * (1 - rhPercent / 100);
  if (!Number.isFinite(vpd)) return null;
  return Math.round(vpd * 100) / 100;
}
