// @generated by scripts/sync-edge-shared.mjs — DO NOT EDIT.
// Source: src/lib/entitlements/planCatalog.ts
// sha256: 65e646ada63a4b4abf9d74d855e147845e496fad8137d7601c3cb5ebbc7be610
// To regenerate: bun run sync-edge-shared

/**
 * PLAN_CATALOG — code-defined mapping from plan_id → Capabilities.
 *
 * Pure data. No React, no Supabase, no fetch, no time reads.
 *
 * Invariants enforced by tests:
 *  - pro_monthly and pro_annual resolve to IDENTICAL capabilities, and likewise
 *    craft_monthly and craft_annual (cadence/price differ in billing, not caps).
 *  - founder_lifetime is Pro-equivalent BUT aiMonthlyCredits is HARD-PINNED
 *    at 100 — never null, never Infinity, never "unlimited". This is the
 *    deliberate defusing of the lifetime AI-cost risk and must not change
 *    without an explicit product decision.
 *  - `blueprint` (the Pro Blueprint overlay) is Craft-exclusive, plus Founder.
 */

import type { Capabilities, PlanId } from "./types.ts";
import { FREE_CAPABILITIES } from "./capabilities.ts";

const PRO_CAPABILITIES: Readonly<Capabilities> = Object.freeze({
  maxActiveGrows: null,
  aiCreditsPerGrow: null,
  aiMonthlyCredits: 100,
  liveSensors: true,
  advancedExports: true,
  multiTent: true,
  sensorHistoryDays: null,
  prioritySupport: true,
  blueprint: false,
});

/**
 * Craft: everything Pro has, plus the Blueprint overlay and a larger monthly
 * AI-credit bucket. The craft-grower / rosin tier.
 */
const CRAFT_CAPABILITIES: Readonly<Capabilities> = Object.freeze({
  ...PRO_CAPABILITIES,
  aiMonthlyCredits: 300,
  blueprint: true,
});

/**
 * Founder Lifetime: Pro capabilities forever. AI credits are intentionally
 * the same 100/month cap as Pro — never unlimited. Founders keep the Blueprint
 * overlay (they are the earliest premium supporters).
 */
const FOUNDER_LIFETIME_CAPABILITIES: Readonly<Capabilities> = Object.freeze({
  ...PRO_CAPABILITIES,
  aiMonthlyCredits: 100,
  blueprint: true,
});

export const PLAN_CATALOG: Readonly<Record<PlanId, Readonly<Capabilities>>> = Object.freeze({
  free: FREE_CAPABILITIES,
  pro_monthly: PRO_CAPABILITIES,
  pro_annual: PRO_CAPABILITIES,
  craft_monthly: CRAFT_CAPABILITIES,
  craft_annual: CRAFT_CAPABILITIES,
  founder_lifetime: FOUNDER_LIFETIME_CAPABILITIES,
});

export const KNOWN_PLAN_IDS: ReadonlyArray<PlanId> = [
  "free",
  "pro_monthly",
  "pro_annual",
  "craft_monthly",
  "craft_annual",
  "founder_lifetime",
];

export function isKnownPlanId(value: unknown): value is PlanId {
  return typeof value === "string" && (KNOWN_PLAN_IDS as ReadonlyArray<string>).includes(value);
}
