// @generated by scripts/sync-edge-shared.mjs — DO NOT EDIT.
// Source: src/lib/aiDoctorManualTentSensorSnapshotAdapter.ts
// sha256: c1dc99f58fa7f9c85592fdc8367177722702be4d91d5f8bce892c1250e3e816b
// To regenerate: bun run sync-edge-shared

import { AI_DOCTOR_CONTEXT_READINESS_CONFIG } from "../constants/aiDoctorContextReadiness.ts";
import { SOIL_MOISTURE_STUCK_VALUES } from "../constants/sensorTruthRanges.ts";
import type { AiDoctorContextManualSnapshotInput } from "./aiDoctorContextRules.ts";
import {
  MANUAL_CORRECTION_METRICS,
  type ManualCorrectionMetric,
} from "./manualSensorCorrectionContext.ts";
import { isPpfdValid } from "./ppfdRules.ts";
import { resolveSensorObservationTime } from "./sensorObservationTimeRules.ts";
import { classifyManualMetric, isHumidityStuckExtreme } from "./sensorTruthRules.ts";

export interface AiDoctorManualTentSensorRowLike {
  readonly tent_id?: unknown;
  readonly source?: unknown;
  readonly quality?: unknown;
  readonly captured_at?: unknown;
  readonly capturedAt?: unknown;
  readonly ts?: unknown;
  readonly metric?: unknown;
  readonly value?: unknown;
}

export interface AiDoctorManualTentSensorSnapshotAdapterOptions {
  readonly tentId: string;
  readonly now: number | Date;
  readonly existingSnapshots?: readonly AiDoctorContextManualSnapshotInput[];
}

interface ObservationGroup {
  readonly atMs: number;
  readonly atIso: string;
  hasPlausibleMetric: boolean;
  hasInvalidRecognizedMetric: boolean;
}

const RECOGNIZED_METRICS: ReadonlySet<string> = new Set(MANUAL_CORRECTION_METRICS);

function epochOf(value: AiDoctorContextManualSnapshotInput["at"]): number | null {
  if (value == null) return null;
  if (value instanceof Date) {
    const ms = value.getTime();
    return Number.isFinite(ms) ? ms : null;
  }
  if (typeof value === "number") return Number.isFinite(value) ? value : null;
  if (typeof value !== "string" || value.trim().length === 0) return null;
  const ms = Date.parse(value);
  return Number.isFinite(ms) ? ms : null;
}

function nowEpoch(value: number | Date): number | null {
  if (value instanceof Date) {
    const ms = value.getTime();
    return Number.isFinite(ms) ? ms : null;
  }
  return Number.isFinite(value) ? value : null;
}

function hasUsablePersistedQuality(row: AiDoctorManualTentSensorRowLike): boolean {
  if (row.quality === null || row.quality === undefined) return true;
  return typeof row.quality === "string" && row.quality.trim().toLowerCase() === "ok";
}

/**
 * Map persisted Quick Log / sensor_readings metric names onto the
 * correction allow-list. `temp_f` / `humidity` are the live save keys;
 * temperature is converted to °C before plausibility so 76°F is not
 * scored as an implausible Celsius value.
 */
function canonicalizeRecognizedMetric(
  value: unknown,
  numeric: unknown,
): { metric: ManualCorrectionMetric; value: number } | null {
  if (typeof value !== "string" || typeof numeric !== "number" || !Number.isFinite(numeric)) {
    return null;
  }
  const metric = value.trim().toLowerCase();
  if (metric === "temperature_c") return { metric: "temperature_c", value: numeric };
  if (metric === "temp_f" || metric === "temperature_f") {
    return { metric: "temperature_c", value: ((numeric - 32) * 5) / 9 };
  }
  if (metric === "humidity_pct" || metric === "humidity") {
    return { metric: "humidity_pct", value: numeric };
  }
  if (metric === "vpd_kpa" || metric === "vpd") return { metric: "vpd_kpa", value: numeric };
  if (metric === "co2_ppm" || metric === "co2") return { metric: "co2_ppm", value: numeric };
  if (metric === "soil_moisture_pct" || metric === "soil_moisture") {
    return { metric: "soil_moisture_pct", value: numeric };
  }
  if (metric === "ppfd") return { metric: "ppfd", value: numeric };
  if (!RECOGNIZED_METRICS.has(metric)) return null;
  return { metric: metric as ManualCorrectionMetric, value: numeric };
}

function isPlausibleMetric(metric: ManualCorrectionMetric, value: unknown): boolean {
  if (typeof value !== "number" || !Number.isFinite(value)) return false;
  if (metric === "ppfd") return isPpfdValid(value);
  if (!classifyManualMetric(metric, value).valid) return false;
  if (metric === "humidity_pct" && isHumidityStuckExtreme(value)) return false;
  if (
    metric === "soil_moisture_pct" &&
    (SOIL_MOISTURE_STUCK_VALUES as readonly number[]).includes(value)
  ) {
    return false;
  }
  return true;
}

export function manualTentSensorRowsToAiDoctorContextSnapshots(
  rows: readonly AiDoctorManualTentSensorRowLike[] | null | undefined,
  options: AiDoctorManualTentSensorSnapshotAdapterOptions,
): AiDoctorContextManualSnapshotInput[] {
  const now = nowEpoch(options.now);
  if (now === null || typeof options.tentId !== "string" || options.tentId.trim().length === 0) {
    return [];
  }

  const existingTimes = new Set<number>();
  for (const snapshot of options.existingSnapshots ?? []) {
    const atMs = epochOf(snapshot?.at);
    if (atMs !== null) existingTimes.add(atMs);
  }

  const groups = new Map<number, ObservationGroup>();
  for (const row of rows ?? []) {
    if (!row || row.tent_id !== options.tentId || row.source !== "manual") {
      continue;
    }
    if (!hasUsablePersistedQuality(row)) continue;

    const canonical = canonicalizeRecognizedMetric(row.metric, row.value);
    if (!canonical) continue;
    const metric = canonical.metric;

    const rawTime = resolveSensorObservationTime(row);
    if (rawTime === null) continue;
    const atMs = Date.parse(rawTime);
    if (!Number.isFinite(atMs)) continue;
    const ageMs = now - atMs;
    if (ageMs < 0 || ageMs > AI_DOCTOR_CONTEXT_READINESS_CONFIG.recentEventWindowMs) continue;

    let group = groups.get(atMs);
    if (!group) {
      group = {
        atMs,
        atIso: new Date(atMs).toISOString(),
        hasPlausibleMetric: false,
        hasInvalidRecognizedMetric: false,
      };
      groups.set(atMs, group);
    }

    if (isPlausibleMetric(metric, canonical.value)) {
      group.hasPlausibleMetric = true;
    } else {
      group.hasInvalidRecognizedMetric = true;
    }
  }

  return [...groups.values()]
    .filter(
      (group) =>
        group.hasPlausibleMetric &&
        !group.hasInvalidRecognizedMetric &&
        !existingTimes.has(group.atMs),
    )
    .sort((a, b) => b.atMs - a.atMs || a.atIso.localeCompare(b.atIso))
    .map((group) => ({ at: group.atIso, severity: "ok" }));
}
