// @generated by scripts/sync-edge-shared.mjs — DO NOT EDIT.
// Source: src/lib/aiDoctorReviewGroundingRules.ts
// sha256: 1e379d51d260797f419952a11c9c58f32deb0f6b6898ff425b5df1c2866c3ef6
// To regenerate: bun run sync-edge-shared

/**
 * aiDoctorReviewGroundingRules — narrow, pure semantic fence for a structurally
 * valid AI Doctor review and its already-validated request packet.
 *
 * This is deliberately a reject-only backstop. It does not rewrite model text,
 * manufacture missing evidence, promote sensor provenance, or make a diagnosis.
 * It catches only direct, deterministic safety failures that the structural
 * result contract cannot relate to the packet that prompted the review.
 */

import type { AiDoctorReviewRequestPacket } from "./aiDoctorReviewRequestPacket.ts";
import type { AiDoctorReviewResult } from "./aiDoctorReviewResultContract.ts";

export type AiDoctorReviewGroundingFailureReason =
  | "high_confidence_without_affirmative_evidence"
  | "missing_information_required"
  | "absolute_certainty"
  | "claim_not_supported_by_packet"
  | "healthy_environment_without_trustworthy_snapshot"
  | "automation_or_device_language";

export type AiDoctorReviewGroundingValidation =
  { ok: true } | { ok: false; reason: AiDoctorReviewGroundingFailureReason };

const ABSOLUTE_CERTAINTY_RE =
  /\b(?:definitely|absolutely|undeniably|unquestionably|certainly|guaranteed?|proven|conclusive(?:ly)?|obviously)\b|\b(?:no|without)\s+(?:any\s+)?doubt\b|\bwithout\s+question\b|\bno\s+other\s+explanation\b|\b100\s?%\s+(?:certain|sure|confident|positive)\b/i;

// This is deliberately a directive prefix, not a broad "not"/"without"
// exemption. A limitation such as "the environment is stable without a
// snapshot" must still be rejected rather than accidentally treated as safe.
const CAUTIOUS_DIRECTIVE_PREFIX_RE =
  /^\s*(?:(?:caution|note)\s*:\s*)?(?:do\s+not|do\s*n['’]t|don['’]t|never|avoid|should\s*not|shouldn['’]t|must\s*not|mustn['’]t|refrain\s+from)\b/i;

const AUTOMATION_RE =
  /\b(?:automatically|autonomously|autopilot|automatic(?:ally)?|auto[-\s]?(?:adjust|control|operate|dose|water|irrigate|execute|approve|apply|run)|self[-\s]?(?:adjust|control|operate|dose|water|irrigate))\b/i;

const DEVICE_NOUN_RE =
  /\b(?:fan|fans|light|lights|pump|pumps|heater|heaters|humidifier|humidifiers|dehumidifier|dehumidifiers|valve|valves|relay|actuator|outlet|socket|controller|controllers|hvac|exhaust|intake|dosing|injector|irrigation|sprinkler|device|devices|equipment)\b/i;

const CONTROL_ACTION_RE =
  /\b(?:turn|switch|enable|disable|activate|deactivate|toggle|trigger|power|adjust|control|operate|dose|water|irrigate|execute|dispatch)\b/i;

const ENVIRONMENT_NOUN_RE =
  /\b(?:environment(?:al)?|room|tent|conditions?|temperature|temp|humidity|rh|vpd|air)\b/i;

const STABLE_OR_HEALTHY_RE =
  /\b(?:stable|healthy|optimal|ideal|balanced|normal|within\s+(?:a\s+)?healthy\s+range)\b/i;

const NON_AFFIRMATIVE_EVIDENCE_RE =
  /^\s*(?:no|none|missing|unavailable|unknown|stale|invalid|demo|insufficient)\b|\b(?:cannot|can['’]t)\s+(?:confirm|determine|verify|support)\b/i;

type MetricKey =
  "temperature" | "humidity" | "vpd" | "ph" | "ec" | "ppm" | "moisture" | "co2" | "ppfd";

const METRIC_ALIASES: Readonly<Record<MetricKey, readonly string[]>> = Object.freeze({
  temperature: ["temperature", "temp"],
  humidity: ["humidity", "rh"],
  vpd: ["vpd"],
  ph: ["ph"],
  ec: ["ec"],
  ppm: ["ppm"],
  moisture: ["moisture"],
  co2: ["co2"],
  ppfd: ["ppfd"],
});

const NUMBER_RE = /-?\d+(?:\.\d+)?/;

type CanonicalMetricUnit =
  "temperature_c" | "percent" | "kpa" | "ph" | "ec_ms_per_cm" | "ppm" | "ppfd";

interface CanonicalMetricValue {
  value: number;
  unit: CanonicalMetricUnit;
}

const METRIC_CLAIM_UNIT_SOURCES: Readonly<Record<MetricKey, string | null>> = Object.freeze({
  // A slash after a temperature token (for example, "C/F") is ambiguous;
  // reject it instead of accepting the leading C or F fragment.
  temperature: "(?:°?\\s*[CF]\\b(?!\\s*\\/)|celsius\\b(?!\\s*\\/)|fahrenheit\\b(?!\\s*\\/))",
  humidity: "(?:%|percent(?:age)?)",
  vpd: "(?:kpa)",
  // pH is conventionally unitless; the metric name itself supplies its unit.
  ph: null,
  // A slash after a complete conductivity unit (for example, "mS/cm/uS")
  // makes the claim ambiguous; never accept only its valid leading fragment.
  ec: "(?:(?:m|[uµμ])\\s*s\\s*(?:\\/|per)\\s*cm|(?:milli|micro)\\s*siemens\\s*(?:\\/|per)\\s*cm)(?!\\s*\\/)",
  ppm: "(?:ppm)",
  moisture: "(?:%|percent(?:age)?)",
  co2: "(?:ppm)",
  ppfd: "(?:[uµμ]\\s*mol\\s*(?:\\/|per)\\s*m(?:2|²)\\s*(?:\\/|per)\\s*s|[uµμ]mol\\s*m-2\\s*s-1)",
});

const LOGGED_EVENT_CLAIMS: readonly {
  category: AiDoctorReviewRequestPacket["recentEvents"][number]["category"];
  pattern: RegExp;
}[] = [
  {
    category: "watering",
    pattern:
      /\b(?:watered|irrigated)\b|\b(?:recent|last)\s+(?:watering|irrigation)\b|\b(?:watering|irrigation)\s+(?:event|log(?:ged)?|record|entry)\b/i,
  },
  {
    category: "feeding",
    pattern:
      /\b(?:fed|fertili[sz]ed)\b|\b(?:recent|last)\s+(?:feeding|feed|fertili[sz](?:er|ing))\b|\b(?:feeding|feed|fertili[sz](?:er|ing))\s+(?:event|log(?:ged)?|record|entry)\b/i,
  },
  {
    category: "photos",
    pattern:
      /\b(?:recent|attached|provided)\s+photos?\b|\bphotos?\s+(?:show|shows|indicate|indicates|reveal|reveals)\b/i,
  },
];

const DIRECT_SNAPSHOT_CLAIM_RE =
  /\b(?:recent|latest|current)\s+(?:sensor\s+)?snapshot\b|\b(?:sensor\s+)?snapshot\s+(?:shows?|reads?|indicates?)\b/i;

const SOURCE_LABELED_SNAPSHOT_CLAIM_RE = /\bsource[-\s]labeled\s+(?:sensor\s+)?snapshot\b/i;

const CONTEXT_ABSENCE_SUBJECT_SOURCE =
  "(?:(?:source[-\\s]labeled\\s+)?(?:(?:current|recent|latest)\\s+)?(?:sensor\\s+)?snapshot|(?:recent|last)\\s+(?:watering|irrigation|feeding|feed|fertili[sz](?:er|ing)?|photos?)|(?:watering|irrigation|feeding|feed|fertili[sz](?:er|ing)?)(?:\\s+(?:event|log(?:ged)?|record|entry))|(?:recent|attached|provided)\\s+photos?)";

const LEADING_CONTEXT_ABSENCE_RE = new RegExp(
  `^\\s*(?:there\\s+(?:is|are)\\s+)?(?:no|none)\\s+${CONTEXT_ABSENCE_SUBJECT_SOURCE}\\b`,
  "i",
);

const NEGATED_CONTEXT_ABSENCE_RE = new RegExp(
  `^\\s*(?:there\\s+(?:is|are)\\s+)?(?:no|none)\\s+${CONTEXT_ABSENCE_SUBJECT_SOURCE}\\b[^.!?;]{0,80}\\b(?:is|are|was|were|remains)\\s+(?:missing|unavailable|unknown|insufficient|stale|invalid)\\b`,
  "i",
);

const SUBJECT_CONTEXT_ABSENCE_RE = new RegExp(
  `\\b${CONTEXT_ABSENCE_SUBJECT_SOURCE}\\b[^.!?;]{0,80}\\b(?:is|are|was|were|remains|not)\\s+(?:missing|unavailable|unknown|insufficient|stale|invalid|not\\s+(?:available|present|recorded|provided|included))\\b`,
  "i",
);

const LEADING_CONTEXT_UNCERTAINTY_RE = new RegExp(
  `^\\s*(?:cannot|can['’]t|unable\\s+to)\\s+(?:confirm|determine|verify|support|establish|find|locate)\\b[^.!?;]{0,120}\\b${CONTEXT_ABSENCE_SUBJECT_SOURCE}\\b`,
  "i",
);

function outputTexts(result: AiDoctorReviewResult): readonly string[] {
  return [
    result.summary,
    result.likely_issue,
    ...result.evidence,
    ...result.missing_information,
    ...result.possible_causes,
    result.immediate_action,
    result.what_not_to_do,
    result.twenty_four_hour_follow_up,
    result.three_day_recovery_plan,
    ...(result.action_queue_suggestion
      ? [result.action_queue_suggestion.title, result.action_queue_suggestion.rationale]
      : []),
  ];
}

/** User-visible fields normally used to make affirmative context assertions. */
function contextClaimTexts(result: AiDoctorReviewResult): readonly string[] {
  return [
    result.summary,
    result.likely_issue,
    ...result.evidence,
    ...result.possible_causes,
    result.immediate_action,
    result.what_not_to_do,
    result.twenty_four_hour_follow_up,
    result.three_day_recovery_plan,
    ...(result.action_queue_suggestion
      ? [result.action_queue_suggestion.title, result.action_queue_suggestion.rationale]
      : []),
  ];
}

/**
 * Missing-information text is still untrusted model output: it can fabricate
 * a measurement, certainty, event, or snapshot claim. The event/snapshot
 * detector separately recognizes explicit absence wording such as "a snapshot
 * is missing" as a legitimate uncertainty disclosure.
 */
function directClaimTexts(result: AiDoctorReviewResult): readonly string[] {
  return [...contextClaimTexts(result), ...result.missing_information];
}

function splitClauses(text: string): readonly string[] {
  // A decimal point is part of a numeric measurement, not a clause boundary.
  return text.split(/\.(?!\d)|[!?;\n,]+|[\u2014\u2013]|\s-\s|\b(?:but|however|instead|then)\b/i);
}

function isCautiousDirective(clause: string): boolean {
  return CAUTIOUS_DIRECTIVE_PREFIX_RE.test(clause);
}

function isNonAffirmativeStabilityClause(clause: string): boolean {
  return (
    /\b(?:cannot|can['’]t|unable\s+to)\s+(?:confirm|determine|verify|establish|call|say|know)\b[^.!?;]{0,120}\b(?:stable|healthy|optimal|ideal|balanced|normal)\b/i.test(
      clause,
    ) ||
    /\b(?:stable|healthy|optimal|ideal|balanced|normal)\b[^.!?;]{0,120}\b(?:cannot|can['’]t|unable\s+to)\s+(?:be\s+)?(?:confirmed|determined|verified|established|called|said|known)\b/i.test(
      clause,
    ) ||
    /\b(?:stable|healthy|optimal|ideal|balanced|normal)\b\s+(?:is\s+)?(?:unknown|uncertain|unconfirmed|unverified)\b/i.test(
      clause,
    )
  );
}

function isNonAffirmativeContextDisclosure(clause: string): boolean {
  // "No watering event is missing" is a double negative, not a disclosure
  // that the packet lacks a watering event. Fail closed rather than letting it
  // suppress a later positive event or snapshot claim in the same clause.
  if (NEGATED_CONTEXT_ABSENCE_RE.test(clause)) return false;
  return (
    LEADING_CONTEXT_ABSENCE_RE.test(clause) ||
    SUBJECT_CONTEXT_ABSENCE_RE.test(clause) ||
    LEADING_CONTEXT_UNCERTAINTY_RE.test(clause)
  );
}

function hasTrustworthyAnnotatedSnapshot(packet: AiDoctorReviewRequestPacket): boolean {
  const annotation = packet.recentSensorSnapshotAnnotation;
  return Boolean(
    packet.recentSensorSnapshot &&
    packet.recentSensorSnapshot.severity !== "invalid" &&
    annotation &&
    annotation.includesValues &&
    !annotation.stale &&
    (annotation.source === "live" || annotation.source === "manual") &&
    (annotation.trust === "medium" || annotation.trust === "high"),
  );
}

function packetNeedsMissingInformation(packet: AiDoctorReviewRequestPacket): boolean {
  const annotation = packet.recentSensorSnapshotAnnotation;
  return (
    packet.readiness.state !== "strong" ||
    packet.readiness.missing.length > 0 ||
    packet.missingLiveSensorReadings === true ||
    Boolean(
      annotation &&
      (!annotation.includesValues ||
        annotation.stale ||
        annotation.trust === "low" ||
        (annotation.source !== "live" && annotation.source !== "manual")),
    )
  );
}

function packetHasAffirmativeEvidence(packet: AiDoctorReviewRequestPacket): boolean {
  return (
    packet.readiness.evidence.some((item) => !NON_AFFIRMATIVE_EVIDENCE_RE.test(item)) ||
    packet.recentEvents.length > 0 ||
    (packet.recentRootZoneObservations?.length ?? 0) > 0 ||
    hasTrustworthyAnnotatedSnapshot(packet)
  );
}

function resultHasAffirmativeEvidence(result: AiDoctorReviewResult): boolean {
  return result.evidence.some((item) => !NON_AFFIRMATIVE_EVIDENCE_RE.test(item));
}

function hasUnsafeAutomationOrDeviceLanguage(result: AiDoctorReviewResult): boolean {
  for (const text of outputTexts(result)) {
    for (const rawClause of splitClauses(text)) {
      const clause = rawClause.trim();
      if (!clause || isCautiousDirective(clause)) continue;
      const hasAutomation = AUTOMATION_RE.test(clause);
      const hasDevice = DEVICE_NOUN_RE.test(clause);
      const hasControlAction = CONTROL_ACTION_RE.test(clause);
      if (hasAutomation || (hasDevice && hasControlAction)) return true;
    }
  }
  return false;
}

function hasAbsoluteCertainty(result: AiDoctorReviewResult): boolean {
  return directClaimTexts(result).some((text) =>
    splitClauses(text).some(
      (clause) => !isCautiousDirective(clause) && ABSOLUTE_CERTAINTY_RE.test(clause),
    ),
  );
}

function hasTrustworthyEnvironmentSnapshot(packet: AiDoctorReviewRequestPacket): boolean {
  if (!hasTrustworthyAnnotatedSnapshot(packet) || packet.recentSensorSnapshot?.severity !== "ok") {
    return false;
  }
  return ["temperature", "humidity", "vpd", "co2"].some(
    (metric) => packetValuesForMetric(packet, metric as MetricKey).length > 0,
  );
}

function claimsStableOrHealthyEnvironment(result: AiDoctorReviewResult): boolean {
  return directClaimTexts(result).some((text) => {
    return splitClauses(text).some(
      (clause) =>
        !isCautiousDirective(clause) &&
        !isNonAffirmativeStabilityClause(clause) &&
        ENVIRONMENT_NOUN_RE.test(clause) &&
        STABLE_OR_HEALTHY_RE.test(clause),
    );
  });
}

function normalizedMetricField(field: string): string {
  return field.toLowerCase().replace(/[^a-z0-9]+/g, " ");
}

function normalizedMetricUnit(unit: string): string {
  return unit
    .toLowerCase()
    .replace(/[µμ]/g, "u")
    .replace(/°/g, "")
    .replace(/²/g, "2")
    .replace(/\s+/g, "")
    .replace(/per/g, "/");
}

/**
 * Normalizes only known, metric-compatible units. Numeric claims without a
 * usable unit fail closed rather than assuming Celsius, percent, or mS/cm.
 */
function toCanonicalMetricValue(
  metric: MetricKey,
  value: number,
  rawUnit: string | undefined,
): CanonicalMetricValue | null {
  if (!Number.isFinite(value)) return null;
  const unit = rawUnit === undefined ? null : normalizedMetricUnit(rawUnit);

  switch (metric) {
    case "temperature":
      if (unit === "c" || unit === "celsius") return { value, unit: "temperature_c" };
      if (unit === "f" || unit === "fahrenheit") {
        return { value: ((value - 32) * 5) / 9, unit: "temperature_c" };
      }
      return null;
    case "humidity":
    case "moisture":
      return unit === "%" || unit === "percent" || unit === "percentage"
        ? { value, unit: "percent" }
        : null;
    case "vpd":
      return unit === "kpa" ? { value, unit: "kpa" } : null;
    case "ph":
      return unit === null || unit === "ph" ? { value, unit: "ph" } : null;
    case "ec":
      if (unit === "ms/cm" || unit === "mscm" || unit === "millisiemens/cm") {
        return { value, unit: "ec_ms_per_cm" };
      }
      if (unit === "us/cm" || unit === "uscm" || unit === "microsiemens/cm") {
        return { value: value / 1000, unit: "ec_ms_per_cm" };
      }
      return null;
    case "ppm":
    case "co2":
      return unit === "ppm" ? { value, unit: "ppm" } : null;
    case "ppfd":
      return unit === "umol/m2/s" || unit === "umolm-2s-1" ? { value, unit: "ppfd" } : null;
  }
}

function packetValuesForMetric(
  packet: AiDoctorReviewRequestPacket,
  metric: MetricKey,
): readonly CanonicalMetricValue[] {
  const readings = packet.recentSensorSnapshot?.readings ?? [];
  const aliases = METRIC_ALIASES[metric];
  return readings
    .filter((reading) => {
      const field = normalizedMetricField(reading.field);
      return aliases.some((alias) => new RegExp(`\\b${alias}\\b`, "i").test(field));
    })
    .map((reading) => toCanonicalMetricValue(metric, reading.value, reading.unit))
    .filter((reading): reading is CanonicalMetricValue => reading !== null);
}

function hasApproximatePacketValue(
  values: readonly CanonicalMetricValue[],
  claimed: CanonicalMetricValue,
): boolean {
  return values.some(
    (value) => value.unit === claimed.unit && Math.abs(value.value - claimed.value) <= 0.001,
  );
}

function hasUnsupportedLoggedEventClaim(
  result: AiDoctorReviewResult,
  packet: AiDoctorReviewRequestPacket,
): boolean {
  for (const text of directClaimTexts(result)) {
    for (const clause of splitClauses(text)) {
      if (isCautiousDirective(clause) || isNonAffirmativeContextDisclosure(clause)) continue;
      for (const claim of LOGGED_EVENT_CLAIMS) {
        if (
          claim.pattern.test(clause) &&
          !packet.recentEvents.some((event) => event.category === claim.category)
        ) {
          return true;
        }
      }
    }
  }
  return false;
}

function hasUnsupportedSnapshotClaim(
  result: AiDoctorReviewResult,
  packet: AiDoctorReviewRequestPacket,
): boolean {
  for (const text of directClaimTexts(result)) {
    for (const clause of splitClauses(text)) {
      if (isCautiousDirective(clause) || isNonAffirmativeContextDisclosure(clause)) continue;
      if (DIRECT_SNAPSHOT_CLAIM_RE.test(clause) && !packet.recentSensorSnapshot) return true;
      if (SOURCE_LABELED_SNAPSHOT_CLAIM_RE.test(clause) && !packet.recentSensorSnapshotAnnotation) {
        return true;
      }
    }
  }
  return false;
}

/**
 * Detects only direct numeric sensor assertions. General diagnosis language is
 * deliberately outside this lexical fence: it needs horticultural judgement,
 * not a brittle string comparison.
 */
function hasDirectUnsupportedPacketClaim(
  result: AiDoctorReviewResult,
  packet: AiDoctorReviewRequestPacket,
): boolean {
  for (const text of directClaimTexts(result)) {
    for (const clause of splitClauses(text)) {
      if (isCautiousDirective(clause)) continue;
      for (const [metric, aliases] of Object.entries(METRIC_ALIASES) as Array<
        [MetricKey, readonly string[]]
      >) {
        const metricAlternation = aliases
          .map((alias) => alias.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"))
          .join("|");
        // Require an assertion connector (or an immediately adjacent table-like
        // value) so "check temperature in 24 hours" is not mistaken for a
        // fabricated reading.
        const unitSource = METRIC_CLAIM_UNIT_SOURCES[metric];
        const metricFirstUnitCapture = unitSource ? `\\s*(${unitSource})?` : "";
        const metricFirst = new RegExp(
          `\\b(?:${metricAlternation})\\b\\s*(?:(?:is|are|was|were|reads?|reading|measured(?:\\s+at)?|shows?|showed|at|of|:|=)\\s*)?(${NUMBER_RE.source})${metricFirstUnitCapture}`,
          "gi",
        );
        const valueFirst = new RegExp(
          unitSource
            ? `(${NUMBER_RE.source})\\s*(${unitSource})\\s+\\b(?:${metricAlternation})\\b`
            : `(${NUMBER_RE.source})\\s+\\b(?:${metricAlternation})\\b`,
          "gi",
        );
        const values = packetValuesForMetric(packet, metric);

        for (const matcher of [metricFirst, valueFirst]) {
          for (const match of clause.matchAll(matcher)) {
            const claimed = toCanonicalMetricValue(
              metric,
              Number(match[1]),
              metric === "ph" ? undefined : match[2],
            );
            if (
              !claimed ||
              !hasTrustworthyAnnotatedSnapshot(packet) ||
              !hasApproximatePacketValue(values, claimed)
            ) {
              return true;
            }
          }
        }
      }
    }
  }
  return (
    hasUnsupportedLoggedEventClaim(result, packet) || hasUnsupportedSnapshotClaim(result, packet)
  );
}

/**
 * Return a stable failure code when a structural result makes a direct unsafe
 * or ungrounded claim against its validated packet. The inputs are never
 * mutated, normalized, persisted, logged, or returned from this helper.
 */
export function validateAiDoctorReviewGrounding(
  result: AiDoctorReviewResult,
  packet: AiDoctorReviewRequestPacket,
): AiDoctorReviewGroundingValidation {
  if (hasUnsafeAutomationOrDeviceLanguage(result)) {
    return { ok: false, reason: "automation_or_device_language" };
  }
  if (hasAbsoluteCertainty(result)) {
    return { ok: false, reason: "absolute_certainty" };
  }
  if (
    result.confidence === "high" &&
    (!packetHasAffirmativeEvidence(packet) || !resultHasAffirmativeEvidence(result))
  ) {
    return { ok: false, reason: "high_confidence_without_affirmative_evidence" };
  }
  if (packetNeedsMissingInformation(packet) && result.missing_information.length === 0) {
    return { ok: false, reason: "missing_information_required" };
  }
  if (claimsStableOrHealthyEnvironment(result) && !hasTrustworthyEnvironmentSnapshot(packet)) {
    return { ok: false, reason: "healthy_environment_without_trustworthy_snapshot" };
  }
  if (hasDirectUnsupportedPacketClaim(result, packet)) {
    return { ok: false, reason: "claim_not_supported_by_packet" };
  }
  return { ok: true };
}
