// @generated by scripts/sync-edge-shared.mjs — DO NOT EDIT.
// Source: src/lib/aiSensorSnapshotContextRules.ts
// sha256: 2155053da3ce6984c2354c62a40890cbc568260ed935dea56a92041893d22a72
// To regenerate: bun run sync-edge-shared

/**
 * Re-export of the canonical, source-aware AI sensor snapshot annotator
 * so vitest (which scans `src/**`) can import it without crossing into
 * `supabase/functions/`. The canonical implementation lives at
 * `supabase/functions/ai-coach/sensorSnapshotContextRules.ts` so the
 * ai-coach edge function bundle can also use it.
 */
export * from "../../supabase/functions/ai-coach/sensorSnapshotContextRules";
