// @generated by scripts/sync-edge-shared.mjs — DO NOT EDIT.
// Source: src/lib/ggsRealPayloadIngestRules.ts
// sha256: a5f86a3c266d63d4158cd8d49d0744cd56a25c504c672f2085f1836eb8d21d05
// To regenerate: bun run sync-edge-shared

/**
 * ggsRealPayloadIngestRules — pure planner that turns a real
 * Spider Farmer GGS 3-in-1 Soil Sensor Pro payload into the exact
 * argument shape required by the existing `pi_ingest_commit_batch`
 * RPC.
 *
 * HARD CONSTRAINTS (stop-ship if violated):
 *   - Pure. No I/O, no Supabase, no fetch, no timers, no console writes.
 *   - REFUSES to fabricate live telemetry. If the payload does not look
 *     like it came from a physical device, this helper returns a typed
 *     refusal — the runner never inserts anything.
 *   - NEVER emits `ggs_live` or `ggs_csv`. Because the transport is an
 *     operator paste, the stored source is `"manual"` even when the payload
 *     came from a physical device.
 *   - Vendor identity belongs in `raw_payload.source_app` only.
 *   - Tent + captured_at + bridge + device + user context are all
 *     required. Missing anything → refusal.
 *   - Values are validated through the existing GGS normalizer; out of
 *     bounds is rejected, NEVER silently clamped.
 *   - Output only contains the three canonical long-format metrics:
 *     `soil_moisture_pct`, `ec`, `soil_temp_c`.
 *   - No alert / Action Queue / AI / device-control hint is produced.
 */
import {
  normalizeGgsSoilSensorReading,
  GGS_SOIL_SENSOR_PROVIDER,
  type GgsSoilReadingDraft,
} from "./ggsSoilSensorReadingNormalizer.ts";

/** Metrics this helper is allowed to emit. */
export type GgsRealPayloadMetric = "soil_moisture_pct" | "ec" | "soil_temp_c";

/**
 * Canonical acquisition-path source stored by the RPC. The physical-device
 * claim is preserved separately in the server-authored provenance envelope.
 */
export const GGS_REAL_PAYLOAD_SOURCE = "manual" as const;

/** Vendor identity stored under raw_payload.source_app. */
export const GGS_REAL_PAYLOAD_SOURCE_APP = GGS_SOIL_SENSOR_PROVIDER; // "spider_farmer_ggs"

/**
 * Explicit source declarations fail closed. An operator attestation can
 * confirm provenance for a payload with no declaration, but it can never
 * override an explicit unknown/synthetic declaration.
 */
export const GGS_ALLOWED_REAL_PAYLOAD_DECLARED_SOURCES = new Set<string>([
  "live",
  GGS_REAL_PAYLOAD_SOURCE_APP,
]);

/** Server-authored provenance stamped on every operator-boundary row. */
export const GGS_OPERATOR_ATTESTED_PROVENANCE = "operator_attested_real_payload" as const;
export const GGS_OPERATOR_ATTESTATION_BOUNDARY = "operator-ggs-real-payload-commit" as const;

export interface GgsRealPayloadContext {
  /** Server-resolved owner UUID. Required. */
  userId: string;
  /** Bridge id (matches the bridge_tokens row). Required. */
  bridgeId: string;
  /** Tent UUID the readings belong to. Required. */
  tentId: string;
  /**
   * Physical probe / device id (e.g. the GGS sensor serial). Required —
   * we will not write rows that lack a device id, because the
   * idempotency table is keyed on it.
   */
  deviceId: string;
  /**
   * Whether the operator checked the real-device attestation for this exact
   * payload/context tuple. The Edge handler re-establishes this from the
   * request after auth/role/ownership checks; client previews are not trusted.
   */
  operatorAttested?: boolean;
  /** Caller-injected clock for deterministic tests. */
  now?: Date;
}

export interface GgsRealPayloadCommitRow {
  /** Stable per-(captured_at, device, metric) idempotency key. */
  idempotency_key: string;
  device_id: string;
  metric: GgsRealPayloadMetric;
  value: number;
  captured_at: string;
  source: typeof GGS_REAL_PAYLOAD_SOURCE; // always "manual"
  quality: "ok" | "degraded";
  raw_payload: GgsRealPayloadAuditEnvelope;
}

export interface GgsRealPayloadAuditEnvelope {
  /** Canonical vendor identity. UI must NEVER render this envelope. */
  source_app: typeof GGS_REAL_PAYLOAD_SOURCE_APP;
  /** Physical identity copied only after exact request/payload binding. */
  sensor_id: string;
  device_id: string;
  /** Stable server-derived identity shared by every row from one payload. */
  cohort_id: string;
  provenance: typeof GGS_OPERATOR_ATTESTED_PROVENANCE;
  operator_attestation: {
    attested: boolean;
    attested_at: string | null;
    boundary: typeof GGS_OPERATOR_ATTESTATION_BOUNDARY;
  };
  captured_at: string;
  /** Per-metric unit annotation, when conversion was applied. */
  original_units?: Record<string, string>;
  /** Verbatim raw payload for audit. */
  payload: unknown;
}

export type GgsRealPayloadRefusalReason =
  | "payload_missing"
  | "payload_not_object"
  | "context_missing"
  | "user_id_missing"
  | "bridge_id_missing"
  | "tent_id_missing"
  | "device_id_missing"
  | "payload_device_id_missing"
  | "payload_device_id_mismatch"
  | "captured_at_missing_or_malformed"
  | "declared_source_not_allowed"
  | "non_finite_value"
  | "soil_temp_out_of_range"
  | "soil_ec_unit_mismatch_suspected"
  | "no_canonical_readings"
  | "normalizer_refused";

export type GgsRealPayloadCommitInput =
  | {
      ok: true;
      userId: string;
      bridgeId: string;
      tentId: string;
      rows: GgsRealPayloadCommitRow[];
      warnings: string[];
    }
  | {
      ok: false;
      reason: GgsRealPayloadRefusalReason;
      details?: string;
    };

function refuse(reason: GgsRealPayloadRefusalReason, details?: string): GgsRealPayloadCommitInput {
  return { ok: false, reason, details };
}

function isNonEmptyString(v: unknown): v is string {
  return typeof v === "string" && v.trim().length > 0;
}

function readDeclaredSource(raw: Record<string, unknown>): string | null {
  const candidates = [raw.source, raw.declared_source, raw.declaredSource];
  for (const c of candidates) {
    if (typeof c === "string" && c.trim().length > 0) return c.trim().toLowerCase();
  }
  return null;
}

function readSensorIds(raw: Record<string, unknown>): string[] {
  const identities: string[] = [];
  for (const k of [
    "sensor_id",
    "sensorId",
    "probe_id",
    "probeId",
    "serial",
    "device_id",
    "deviceId",
    "ggs_id",
    "controller_id",
    "controllerId",
  ] as const) {
    const v = raw[k];
    if (typeof v === "string" && v.trim()) identities.push(v.trim());
    if (typeof v === "number" && Number.isFinite(v)) identities.push(String(v));
  }
  return identities;
}

export function buildGgsRealPayloadCohortId(deviceId: string, capturedAt: string): string {
  return `ggs:${deviceId}:${capturedAt}`;
}

function readOriginalUnits(raw: Record<string, unknown>): Record<string, string> | undefined {
  const v = raw.original_units ?? raw.originalUnits;
  if (!v || typeof v !== "object" || Array.isArray(v)) return undefined;
  const out: Record<string, string> = {};
  for (const [k, val] of Object.entries(v as Record<string, unknown>)) {
    if (typeof val === "string" && val.trim()) out[k] = val.trim();
  }
  return Object.keys(out).length ? out : undefined;
}

/**
 * Plan a `pi_ingest_commit_batch` call from a real GGS payload.
 *
 * Returns a typed refusal if anything is missing, malformed, or smells
 * like fabricated data. Never throws.
 */
export function buildGgsRealPayloadCommitInput(
  payload: unknown,
  ctx: GgsRealPayloadContext,
): GgsRealPayloadCommitInput {
  if (!ctx || typeof ctx !== "object") return refuse("context_missing");
  if (!isNonEmptyString(ctx.userId)) return refuse("user_id_missing");
  if (!isNonEmptyString(ctx.bridgeId)) return refuse("bridge_id_missing");
  if (!isNonEmptyString(ctx.tentId)) return refuse("tent_id_missing");
  if (!isNonEmptyString(ctx.deviceId)) return refuse("device_id_missing");

  if (payload === null || payload === undefined) return refuse("payload_missing");
  if (typeof payload !== "object" || Array.isArray(payload)) {
    return refuse("payload_not_object");
  }
  const raw = payload as Record<string, unknown>;

  const declared = readDeclaredSource(raw);
  if (declared && !GGS_ALLOWED_REAL_PAYLOAD_DECLARED_SOURCES.has(declared)) {
    return refuse("declared_source_not_allowed", declared);
  }

  // Run the existing pure normalizer to validate units, ranges, freshness,
  // tent context, and to detect EC unit mismatches and non-finite values.
  let draft: GgsSoilReadingDraft;
  try {
    draft = normalizeGgsSoilSensorReading(raw, {
      now: ctx.now,
      declaredSource: "live",
    });
  } catch {
    return refuse("normalizer_refused", "normalizer threw");
  }

  if (!draft.captured_at) return refuse("captured_at_missing_or_malformed");
  if (!draft.tent_id || draft.tent_id !== ctx.tentId) {
    return refuse("tent_id_missing", "payload tent_id does not match ctx.tentId");
  }
  if (draft.warnings.includes("non_finite_value")) {
    return refuse("non_finite_value");
  }
  if (draft.warnings.includes("soil_ec_unit_mismatch_suspected")) {
    return refuse("soil_ec_unit_mismatch_suspected");
  }
  if (draft.source !== "live") {
    return refuse("normalizer_refused", `source=${draft.source}`);
  }

  const r = draft.readings;
  if (r.soil_moisture_pct === undefined && r.ec === undefined && r.soil_temp_c === undefined) {
    return refuse("no_canonical_readings");
  }
  // Bounds check (defense in depth — DB trigger also enforces -20..80).
  if (typeof r.soil_temp_c === "number" && (r.soil_temp_c < -20 || r.soil_temp_c > 80)) {
    return refuse("soil_temp_out_of_range");
  }

  const sensorIds = readSensorIds(raw);
  if (sensorIds.length === 0) return refuse("payload_device_id_missing");
  const sensorId = ctx.deviceId.trim();
  if (sensorIds.some((identity) => identity !== sensorId)) {
    return refuse(
      "payload_device_id_mismatch",
      "payload sensor identity does not match request deviceId",
    );
  }
  const originalUnits = readOriginalUnits(raw);
  const capturedAt = new Date(draft.captured_at).toISOString();
  const cohortId = buildGgsRealPayloadCohortId(sensorId, capturedAt);
  const operatorAttested = ctx.operatorAttested === true;

  const envelope: GgsRealPayloadAuditEnvelope = {
    source_app: GGS_REAL_PAYLOAD_SOURCE_APP,
    sensor_id: sensorId,
    device_id: sensorId,
    cohort_id: cohortId,
    provenance: GGS_OPERATOR_ATTESTED_PROVENANCE,
    operator_attestation: {
      attested: operatorAttested,
      attested_at: operatorAttested ? (ctx.now ?? new Date()).toISOString() : null,
      boundary: GGS_OPERATOR_ATTESTATION_BOUNDARY,
    },
    captured_at: capturedAt,
    ...(originalUnits ? { original_units: originalUnits } : {}),
    payload: raw,
  };

  const quality: "ok" | "degraded" = draft.status === "accepted" ? "ok" : "degraded";

  const rows: GgsRealPayloadCommitRow[] = [];
  const idKeyPrefix = cohortId;

  const orderedMetrics: Array<[GgsRealPayloadMetric, number | undefined]> = [
    ["soil_moisture_pct", r.soil_moisture_pct],
    ["ec", r.ec],
    ["soil_temp_c", r.soil_temp_c],
  ];
  for (const [metric, value] of orderedMetrics) {
    if (typeof value !== "number" || !Number.isFinite(value)) continue;
    rows.push({
      idempotency_key: `${idKeyPrefix}:${metric}`,
      device_id: sensorId,
      metric,
      value,
      captured_at: capturedAt,
      source: GGS_REAL_PAYLOAD_SOURCE,
      quality,
      raw_payload: envelope,
    });
  }

  if (rows.length === 0) return refuse("no_canonical_readings");

  return {
    ok: true,
    userId: ctx.userId,
    bridgeId: ctx.bridgeId,
    tentId: ctx.tentId,
    rows,
    warnings: draft.warnings,
  };
}
