// @generated by scripts/sync-edge-shared.mjs — DO NOT EDIT.
// Source: src/lib/paidPlanAllowlist.ts
// sha256: 152c810a22128a8f5d7f242b71c8e66159abed6565915bb05501e2f0a8293830
// To regenerate: bun run sync-edge-shared

/**
 * Paid-plan allowlist — single source of truth.
 *
 * Every consumer of the paid-plan universe (edge function allowlist Set,
 * pinned hardening regex, drift guards) MUST derive from PAID_PLAN_IDS here.
 * Do not maintain a parallel list anywhere else — that is how Craft drifted
 * out of the checkout gate in the first place.
 *
 * Order is significant: the pinned regex asserts the exact source order
 * to catch reordering that could mask an accidental removal.
 *
 * This module intentionally has zero runtime dependencies and imports
 * nothing from `@/…`, so it mirrors cleanly into
 * supabase/functions/_shared/lib/ via scripts/sync-edge-shared.mjs.
 */

/** Ordered list of plan ids checkout may resolve prices for. */
export const PAID_PLAN_IDS = [
  "pro_monthly",
  "pro_annual",
  "craft_monthly",
  "craft_annual",
  "founder_lifetime",
  // One-time AI credit packs. Purchasable price ids (SKU-recognition seam) —
  // NOT plans: they never enter planCatalog / KNOWN_PRICE_TO_PLAN, so a
  // credit purchase can never resolve to a Pro entitlement.
  "credit_pack_50",
  "credit_pack_150",
] as const;

export type PaidPlanId = (typeof PAID_PLAN_IDS)[number];

/** Set form for O(1) allowlist checks. */
export const PAID_PLAN_ALLOWLIST: ReadonlySet<string> = new Set(PAID_PLAN_IDS);

/**
 * One-time SKUs. A purchase here grants CREDITS and must never write a
 * subscriptions row — a $9 pack resolving to plan access would be a revenue
 * and trust failure.
 *
 * Declared as the exception rather than deriving plans from it, because
 * PAID_PLAN_IDS above must stay a literal array: the hardening tests pin its
 * exact source text and order via buildPaidPlanAllowlistSourceRegex.
 */
export const CREDIT_PACK_IDS = ["credit_pack_50", "credit_pack_150"] as const;

export type CreditPackId = (typeof CREDIT_PACK_IDS)[number];

const CREDIT_PACK_ID_SET: ReadonlySet<string> = new Set(CREDIT_PACK_IDS);

// Fail at import time — including edge-function cold start and every test run
// — if a new pack is added to PAID_PLAN_IDS but not declared here. Without
// this, SUBSCRIPTION_PLAN_IDS below would silently classify it as a plan, and
// a credit purchase would grant a subscription. That is the dangerous
// direction of this split, so it is guarded rather than merely documented.
for (const id of PAID_PLAN_IDS) {
  if (id.startsWith("credit_pack") && !CREDIT_PACK_ID_SET.has(id)) {
    throw new Error(
      `paidPlanAllowlist: "${id}" looks like a one-time credit pack but is missing from ` +
        `CREDIT_PACK_IDS. Add it there, or it will be treated as a subscription plan and ` +
        `a pack purchase would grant plan access.`,
    );
  }
}

/**
 * Recurring/lifetime plans — every purchasable id that is NOT a one-time pack.
 *
 * DERIVED, deliberately. `payments-webhook`'s KNOWN_PRICE_IDS was the last
 * hand-maintained copy of this list, and its omission of Craft meant a
 * completed payment wrote no subscriptions row at all while Paddle still
 * received a 200 — charged, granted nothing, silent. Deriving makes that
 * class structurally impossible rather than merely asserted.
 */
export const SUBSCRIPTION_PLAN_IDS: ReadonlyArray<PaidPlanId> = PAID_PLAN_IDS.filter(
  (id) => !CREDIT_PACK_ID_SET.has(id),
);

/**
 * Build the source-order regex the hardening tests pin against
 * `supabase/functions/get-paddle-price/index.ts`. Kept as a builder rather
 * than a constant so the test file can pass just the plan ids it wants to
 * assert on (recurring plans only, credit packs only, etc.).
 *
 * Quote-agnostic because prettier normalizes edge functions to double quotes.
 * Requires the entries to appear in the given order, separated by commas
 * and optional whitespace, inside a PAID_PLAN_ALLOWLIST literal.
 */
export function buildPaidPlanAllowlistSourceRegex(ids: readonly string[] = PAID_PLAN_IDS): RegExp {
  // Separator tolerates whitespace AND intervening line comments (the credit-
  // pack block between founder_lifetime and credit_pack_50).
  const sep = ",[\\s\\S]{0,300}?";
  const entries = ids.map((id) => `["']${id}["']`).join(sep);
  return new RegExp(`PAID_PLAN_IDS\\s*=\\s*\\[[\\s\\S]{0,50}?${entries},`);
}
