// @generated by scripts/sync-edge-shared.mjs — DO NOT EDIT.
// Source: src/lib/plantTypeRules.ts
// sha256: 7b3e2e3723fd16c5b7b812b04026ced47016175fef57cae703414bb14735eeca
// To regenerate: bun run sync-edge-shared

/**
 * plantTypeRules — pure plant-type (autoflower vs photoperiod) normalization
 * and cross-plant comparability.
 *
 * Locked by the autoflower/photoperiod plan (2026-07-21): Verdant never
 * guesses a type. Anything absent, blank, or unrecognized is "unknown", and
 * unknown is never silently comparable — comparison surfaces must surface the
 * gap instead of ranking through it.
 *
 * Stage ranks use the plants-table stage vocabulary (seedling / veg / flower /
 * flush / harvest / cure, with the grow-vocabulary alias "drying" ranked with
 * "cure" per quickLogStageDefaultRules). Deliberately NOT a fourth stage
 * vocabulary — see the stage-alias reconciliation in
 * src/lib/quickLogStageDefaultRules.ts.
 *
 * Pure: no I/O, no React, no Supabase, no timers.
 */

export type PlantType = "autoflower" | "photoperiod" | "unknown";

/** Canonical stored values. Forms map "Not sure" to "unknown". */
export const PLANT_TYPE_VALUES: readonly PlantType[] = ["autoflower", "photoperiod", "unknown"];

const AUTOFLOWER_SYNONYMS = new Set(["autoflower", "autoflowering", "auto", "autos"]);
const PHOTOPERIOD_SYNONYMS = new Set(["photoperiod", "photoperiodic", "photo"]);

/**
 * Normalize any stored/entered value to a PlantType.
 * null / undefined / "" / whitespace / unrecognized → "unknown" — never a
 * silent photoperiod default.
 */
export function normalizePlantType(value: string | null | undefined): PlantType {
  if (typeof value !== "string") return "unknown";
  const v = value.trim().toLowerCase();
  if (v.length === 0) return "unknown";
  if (AUTOFLOWER_SYNONYMS.has(v)) return "autoflower";
  if (PHOTOPERIOD_SYNONYMS.has(v)) return "photoperiod";
  return "unknown";
}

/** True only for a declared autoflower. Unknown is NOT treated as autoflower here. */
export function isAutoflower(type: PlantType | string | null | undefined): boolean {
  return normalizePlantType(type ?? null) === "autoflower";
}

/**
 * Rank of a plants-table stage for comparability distance. Unknown or missing
 * stages rank null (stage distance is then simply not checkable — type
 * honesty is the primary gate; stage visibility is handled by the surfaces).
 */
const PLANT_STAGE_RANK: Readonly<Record<string, number>> = {
  seedling: 1,
  veg: 2,
  flower: 3,
  flush: 4,
  harvest: 5,
  cure: 6,
  drying: 6, // grow-vocabulary alias of cure (STAGE_ALIASES)
};

export function plantStageRank(stage: string | null | undefined): number | null {
  if (typeof stage !== "string") return null;
  const rank = PLANT_STAGE_RANK[stage.trim().toLowerCase()];
  return typeof rank === "number" ? rank : null;
}

/**
 * LOCKED tolerance: plants more than one stage apart are not comparable.
 * Adjacent stages (e.g. veg vs flower) stay comparable; seedling vs flower
 * does not. Changing this number is a contract change — update the plan doc
 * and the unit tests together.
 */
export const PLANT_STAGE_COMPARABILITY_TOLERANCE = 1;

export type ComparabilityReason = "type_unknown" | "type_mismatch" | "stage_mismatch";

export interface ComparabilitySubject {
  readonly plantType?: PlantType | string | null;
  readonly stageRank?: number | null;
}

export interface ComparabilityVerdict {
  readonly comparable: boolean;
  readonly reason?: ComparabilityReason;
}

/**
 * Pairwise comparability. Reason precedence is deliberate:
 *  1. type_unknown  — either side unknown/missing (honesty before matching);
 *  2. type_mismatch — declared autoflower vs declared photoperiod;
 *  3. stage_mismatch — both stage ranks known and further apart than the
 *     locked tolerance.
 * Missing stage ranks never fail the check (null-safe skip).
 */
export function areComparable(
  a: ComparabilitySubject | null | undefined,
  b: ComparabilitySubject | null | undefined,
): ComparabilityVerdict {
  const typeA = normalizePlantType(a?.plantType ?? null);
  const typeB = normalizePlantType(b?.plantType ?? null);
  if (typeA === "unknown" || typeB === "unknown") {
    return { comparable: false, reason: "type_unknown" };
  }
  if (typeA !== typeB) {
    return { comparable: false, reason: "type_mismatch" };
  }
  const rankA = a?.stageRank;
  const rankB = b?.stageRank;
  if (
    typeof rankA === "number" &&
    Number.isFinite(rankA) &&
    typeof rankB === "number" &&
    Number.isFinite(rankB) &&
    Math.abs(rankA - rankB) > PLANT_STAGE_COMPARABILITY_TOLERANCE
  ) {
    return { comparable: false, reason: "stage_mismatch" };
  }
  return { comparable: true };
}

/** Short badge label for presenters: Auto / Photo / Type unknown. */
export function plantTypeBadgeLabel(type: PlantType | string | null | undefined): string {
  const t = normalizePlantType(typeof type === "string" ? type : (type ?? null));
  return t === "autoflower" ? "Auto" : t === "photoperiod" ? "Photo" : "Type unknown";
}
