// @generated by scripts/sync-edge-shared.mjs — DO NOT EDIT.
// Source: src/lib/rootZoneManualObservationRules.ts
// sha256: c594853f2ee05f9aff3ee4b5492544c2f693e06e57b47f6c75679eb4469d4b69
// To regenerate: bun run sync-edge-shared

/**
 * Shared write/read contract for grower-authored root-zone observations.
 *
 * The saved envelope uses the existing snake_case shape in the exact-linked
 * Quick Log companion `diary_entries.details`. Consumers receive a smaller
 * camelCase projection. Both paths are pure, allowlisted, advisory-only, and
 * fail closed on malformed evidence.
 */

export const ROOT_ZONE_MANUAL_OBSERVATION_DETAILS_KEY = "root_zone_manual_observation_v1" as const;
export const ROOT_ZONE_MANUAL_OBSERVATION_SCHEMA_VERSION = 1 as const;
export const ROOT_ZONE_MANUAL_OBSERVATION_EVIDENCE_TYPE = "root_zone_manual_observation" as const;

/** Saved V1 evidence must describe the exact same instant as its linked event. */
export const ROOT_ZONE_MANUAL_OBSERVATION_MAX_EVENT_SKEW_MS = 0;

export const ROOT_ZONE_POT_WEIGHT_FEELS = Object.freeze(["light", "moderate", "heavy"] as const);
export const ROOT_ZONE_MEDIUM_SURFACES = Object.freeze(["dry", "moist", "wet"] as const);
export const ROOT_ZONE_DRAINAGE_OBSERVATIONS = Object.freeze(["normal", "slow", "none"] as const);

export type RootZonePotWeightFeel = (typeof ROOT_ZONE_POT_WEIGHT_FEELS)[number];
export type RootZoneMediumSurface = (typeof ROOT_ZONE_MEDIUM_SURFACES)[number];
export type RootZoneDrainageObservation = (typeof ROOT_ZONE_DRAINAGE_OBSERVATIONS)[number];

/** Exact JSON envelope stored below `details.root_zone_manual_observation_v1`. */
export interface RootZoneManualObservationEnvelopeV1 {
  schema_version: typeof ROOT_ZONE_MANUAL_OBSERVATION_SCHEMA_VERSION;
  source: "manual";
  evidence_type: typeof ROOT_ZONE_MANUAL_OBSERVATION_EVIDENCE_TYPE;
  advisory_only: true;
  observed_at: string;
  pot_weight_feel?: RootZonePotWeightFeel;
  medium_surface?: RootZoneMediumSurface;
  drainage?: RootZoneDrainageObservation;
}

/** Bounded read model. Manual labels are context, never measured telemetry. */
export interface RootZoneManualObservationV1 {
  observedAt: string;
  source: "manual";
  advisoryOnly: true;
  potWeightFeel?: RootZonePotWeightFeel;
  mediumSurface?: RootZoneMediumSurface;
  drainage?: RootZoneDrainageObservation;
}

export interface BuildRootZoneManualObservationEnvelopeV1Input {
  observedAt: string;
  potWeightFeel?: RootZonePotWeightFeel | null;
  mediumSurface?: RootZoneMediumSurface | null;
  drainage?: RootZoneDrainageObservation | null;
}

export type RootZoneManualObservationProjection =
  | { status: "absent" }
  | { status: "invalid" }
  | { status: "valid"; manualObservation: RootZoneManualObservationV1 };

const CANONICAL_ISO_TIMESTAMP_RE = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/;
const ENVELOPE_KEYS = new Set([
  "schema_version",
  "source",
  "evidence_type",
  "advisory_only",
  "observed_at",
  "pot_weight_feel",
  "medium_surface",
  "drainage",
]);
const POT_WEIGHT_FEEL_SET: ReadonlySet<string> = new Set(ROOT_ZONE_POT_WEIGHT_FEELS);
const MEDIUM_SURFACE_SET: ReadonlySet<string> = new Set(ROOT_ZONE_MEDIUM_SURFACES);
const DRAINAGE_SET: ReadonlySet<string> = new Set(ROOT_ZONE_DRAINAGE_OBSERVATIONS);

function asRecord(value: unknown): Record<string, unknown> | null {
  if (!value || typeof value !== "object" || Array.isArray(value)) return null;
  return value as Record<string, unknown>;
}

function hasOwn(record: Record<string, unknown>, key: string): boolean {
  return Object.prototype.hasOwnProperty.call(record, key);
}

function normalizeCanonicalTimestamp(value: unknown): string | null {
  if (typeof value !== "string" || !CANONICAL_ISO_TIMESTAMP_RE.test(value)) return null;
  const timestamp = Date.parse(value);
  if (!Number.isFinite(timestamp)) return null;
  const canonical = new Date(timestamp).toISOString();
  return canonical === value ? canonical : null;
}

function normalizeOptionalLabel<T extends string>(
  record: Record<string, unknown>,
  key: string,
  allowed: ReadonlySet<string>,
): { ok: true; value?: T } | { ok: false } {
  if (!hasOwn(record, key)) return { ok: true };
  const value = record[key];
  return typeof value === "string" && allowed.has(value)
    ? { ok: true, value: value as T }
    : { ok: false };
}

/** Strictly normalize one untrusted V1 storage envelope. */
export function normalizeRootZoneManualObservationEnvelopeV1(
  value: unknown,
): RootZoneManualObservationV1 | null {
  const record = asRecord(value);
  if (!record || Object.keys(record).some((key) => !ENVELOPE_KEYS.has(key))) return null;
  if (
    record.schema_version !== ROOT_ZONE_MANUAL_OBSERVATION_SCHEMA_VERSION ||
    record.source !== "manual" ||
    record.evidence_type !== ROOT_ZONE_MANUAL_OBSERVATION_EVIDENCE_TYPE ||
    record.advisory_only !== true
  ) {
    return null;
  }

  const observedAt = normalizeCanonicalTimestamp(record.observed_at);
  const potWeightFeel = normalizeOptionalLabel<RootZonePotWeightFeel>(
    record,
    "pot_weight_feel",
    POT_WEIGHT_FEEL_SET,
  );
  const mediumSurface = normalizeOptionalLabel<RootZoneMediumSurface>(
    record,
    "medium_surface",
    MEDIUM_SURFACE_SET,
  );
  const drainage = normalizeOptionalLabel<RootZoneDrainageObservation>(
    record,
    "drainage",
    DRAINAGE_SET,
  );
  if (
    observedAt === null ||
    !potWeightFeel.ok ||
    !mediumSurface.ok ||
    !drainage.ok ||
    (potWeightFeel.value === undefined &&
      mediumSurface.value === undefined &&
      drainage.value === undefined)
  ) {
    return null;
  }

  return Object.freeze({
    observedAt,
    source: "manual" as const,
    advisoryOnly: true as const,
    ...(potWeightFeel.value ? { potWeightFeel: potWeightFeel.value } : {}),
    ...(mediumSurface.value ? { mediumSurface: mediumSurface.value } : {}),
    ...(drainage.value ? { drainage: drainage.value } : {}),
  });
}

/** Build the exact saved envelope through the same strict contract used on read. */
export function buildRootZoneManualObservationEnvelopeV1(
  input: BuildRootZoneManualObservationEnvelopeV1Input,
): RootZoneManualObservationEnvelopeV1 | null {
  const candidate: RootZoneManualObservationEnvelopeV1 = {
    schema_version: ROOT_ZONE_MANUAL_OBSERVATION_SCHEMA_VERSION,
    source: "manual",
    evidence_type: ROOT_ZONE_MANUAL_OBSERVATION_EVIDENCE_TYPE,
    advisory_only: true,
    observed_at: input.observedAt,
    ...(input.potWeightFeel ? { pot_weight_feel: input.potWeightFeel } : {}),
    ...(input.mediumSurface ? { medium_surface: input.mediumSurface } : {}),
    ...(input.drainage ? { drainage: input.drainage } : {}),
  };
  return normalizeRootZoneManualObservationEnvelopeV1(candidate) ? Object.freeze(candidate) : null;
}

/**
 * Extract and align the reserved details envelope with its parent grow event.
 * Unrelated/legacy details remain absent; a supplied reserved envelope is
 * either valid in full or rejected in full.
 */
export function projectRootZoneManualObservationFromDetails(
  details: unknown,
  eventOccurredAt: string,
): RootZoneManualObservationProjection {
  try {
    const record = asRecord(details);
    if (!record || !hasOwn(record, ROOT_ZONE_MANUAL_OBSERVATION_DETAILS_KEY)) {
      return { status: "absent" };
    }

    const manualObservation = normalizeRootZoneManualObservationEnvelopeV1(
      record[ROOT_ZONE_MANUAL_OBSERVATION_DETAILS_KEY],
    );
    const eventTimestamp = normalizeCanonicalTimestamp(eventOccurredAt);
    if (
      !manualObservation ||
      eventTimestamp === null ||
      Math.abs(Date.parse(manualObservation.observedAt) - Date.parse(eventTimestamp)) >
        ROOT_ZONE_MANUAL_OBSERVATION_MAX_EVENT_SKEW_MS
    ) {
      return { status: "invalid" };
    }

    return { status: "valid", manualObservation };
  } catch {
    return { status: "invalid" };
  }
}
