// @generated by scripts/sync-edge-shared.mjs — DO NOT EDIT.
// Source: src/lib/sensorObservationTimeRules.ts
// sha256: 9eed9614c03b761a837586b84058f82986e540b6ccdb4430535847de4cb5d932
// To regenerate: bun run sync-edge-shared

/**
 * Resolve the time a sensor observation was actually captured.
 *
 * CSV imports retain their historical `captured_at` while database `ts` can
 * be the import time. Consumers must use this helper for grouping, freshness,
 * latest-snapshot selection, and trend windows so historical rows never turn
 * into apparent fresh telemetry.
 */
export interface SensorObservationTimeLike {
  ts?: unknown;
  captured_at?: unknown;
  capturedAt?: unknown;
}

function nonEmptyTimestamp(value: unknown): string | null {
  return typeof value === "string" && value.trim().length > 0 ? value.trim() : null;
}

export function resolveSensorObservationTime(row: SensorObservationTimeLike): string | null {
  return (
    nonEmptyTimestamp(row.captured_at) ??
    nonEmptyTimestamp(row.capturedAt) ??
    nonEmptyTimestamp(row.ts)
  );
}
