// @generated by scripts/sync-edge-shared.mjs — DO NOT EDIT.
// Source: src/lib/sensorSnapshot.ts
// sha256: ab526b76115c17ab829fd25449a6dce925cf537dbdbda459e1a73e97ffd63511
// To regenerate: bun run sync-edge-shared

/**
 * Pure helpers for the scoped Dashboard "Latest Environment" card.
 *
 * No I/O, no Supabase calls, no React. Read-only derivations only.
 * NOT an AI diagnosis. NOT live device control.
 */

import { normalizeQuickLogSnapshotMetrics } from "./quick-log/quickLogSnapshotMetricNormalizer.ts";
import {
  isHumidityValid,
  isTemperatureValid,
  isVpdValid,
} from "./sensorReadingNormalizationRules.ts";
import { fahrenheitToCelsius } from "./temperatureUnits.ts";
import { summarizeCsvVendor } from "./sensorReadingVendorLineage.ts";
import { isSensorTestbenchRow } from "./sensorTestbenchIndicatorRules.ts";
import { resolveSensorObservationTime } from "./sensorObservationTimeRules.ts";
import {
  isCurrentStateStale,
  LIVE_CURRENT_STATE_STALE_MS,
  resolveCurrentStateStaleWindowMs,
} from "./sensorTruthCanon.ts";
import { isVerifiedSnapshotLiveRowSource } from "./sensorLiveMembership.ts";

import { SENSOR_SNAPSHOT_STALE_THRESHOLD_MS } from "../constants/sensorTiming.ts";
export type SnapshotSource =
  | "live"
  | "manual"
  | "sim"
  | "diary"
  | "csv"
  | "unavailable"
  /**
   * Rows exist but their `source` is not a recognized trust value (raw
   * vendor strings like "ecowitt"/"pi_bridge", canonical "stale"/"invalid",
   * or anything unexpected). Never rendered as "Live sensor" — claiming
   * live requires every row at the timestamp to literally say "live".
   */
  | "unverified";

/**
 * Per-metric provenance ref keys for {@link SensorSnapshot.metric_refs}.
 * Mirrors the {@link import("./environmentTargetComparison.ts").MetricKey}
 * union; redeclared locally to avoid a circular import. Keep both lists
 * in sync if a new metric is added.
 */
export type SensorSnapshotMetricRefKey =
  "temp" | "rh" | "vpd" | "soil" | "soil_ec" | "soil_temp" | "ppfd";

/**
 * Provenance for a single metric in a snapshot. Carries ONLY the safe
 * id + captured_at + raw source from the EXACT `sensor_readings` row
 * already selected by {@link snapshotFromReadings} for that metric.
 * Never carries raw_payload, never inferred, never "nearest" matched.
 */
export interface SensorSnapshotMetricRef {
  id: string;
  captured_at: string;
  source: string;
}

/**
 * Provenance for a diary-backed Environment Check snapshot. Carries ONLY
 * the EXACT `diary_entries.id` + `entry_at` already known when the
 * snapshot was built from that row. Distinct from {@link SensorSnapshotMetricRef}
 * so diary ids never masquerade as `sensor_readings` rows (see #603).
 * Never carries details/raw_payload/note body.
 */
export interface SensorSnapshotDiaryEvidenceRef {
  id: string;
  entry_at: string;
}

export interface SensorSnapshot {
  source: SnapshotSource;
  ts: string | null;
  temp: number | null;
  rh: number | null;
  vpd: number | null;
  co2: number | null;
  soil: number | null;
  soil_ec: number | null;
  soil_temp: number | null;
  ppfd: number | null;
  /**
   * Raw `device_id` from the contributing sensor row (when one is
   * available). Display surfaces pair this with `source` via
   * `formatSensorSourceLabel` to render labels like
   * "Manual reading · EcoWitt WH45 CO2/THP Monitor" without ever upgrading
   * a manual row to live.
   */
  device_id?: string | null;
  /**
   * CSV vendor lineage hint summarized from the contributing CSV rows'
   * upstream provenance envelope (vendor app name only — payload
   * contents are never read or returned by this file; see
   * `summarizeCsvVendor` for the only access path).
   * Presentation-only — NEVER promotes a reading to "live".
   * `"multiple"` is used when multiple CSV vendors are present at the
   * latest timestamp.
   */
  csvVendor?: import("./sensorSourceDisplayLabel.ts").CsvVendorSummary;
  /**
   * Per-metric provenance for environment alert ref population. Each
   * entry is the EXACT `sensor_readings` row selected by
   * `snapshotFromReadings` for that metric — same id, same `ts` (as
   * `captured_at`), same raw `source`. Only present when the underlying
   * row carried an `id`. Diary-derived snapshots never populate this.
   */
  metric_refs?: Partial<Record<SensorSnapshotMetricRefKey, SensorSnapshotMetricRef>>;
  /**
   * Diary-row provenance for manual Environment Check or Quick Log manual
   * sensor snapshots. Populated only when the adapter receives the exact
   * originating `diary_entries.id`. Never present on sensor_readings-derived
   * snapshots. Never confusable with {@link metric_refs}.
   */
  diary_evidence_ref?: SensorSnapshotDiaryEvidenceRef;
  /**
   * Whether this evidence may back an automatically persisted environment
   * alert. Omitted preserves the existing eligibility contract; only the
   * Plant Quick Log manual snapshot adapter sets this to false because its
   * diary payload is display evidence, not a sensor row or an Environment
   * Check observation.
   */
  alert_persistence_eligible?: boolean;
  /**
   * Tent the contributing rows came from, when they UNAMBIGUOUSLY share
   * one. Environment alerts persist this so tent-scoped surfaces (e.g.
   * Plant Detail's assigned-tent alerts panel) can attribute a breach to
   * the tent whose readings produced it.
   *
   * Deliberately null when the evidence spans several tents — the
   * Dashboard's "All tents" view genuinely mixes rows, and inventing a
   * winner there would attach a real breach to an arbitrary tent. Null is
   * the honest answer and matches this file's never-invent-provenance
   * posture. Carried ON the snapshot rather than beside it so attribution
   * can never drift from the evidence it describes.
   */
  tent_id?: string | null;
}

export const EMPTY_SNAPSHOT: SensorSnapshot = {
  source: "unavailable",
  ts: null,
  temp: null,
  rh: null,
  vpd: null,
  co2: null,
  soil: null,
  soil_ec: null,
  soil_temp: null,
  ppfd: null,
  device_id: null,
  csvVendor: null,
  tent_id: null,
};

/** Coerce numeric DB values; returns null for null/undefined/NaN/Infinity. */
export function toFiniteNumber(v: unknown): number | null {
  if (v === null || v === undefined) return null;
  const n = typeof v === "number" ? v : Number(v);
  return Number.isFinite(n) ? n : null;
}

export const SOURCE_LABEL: Record<SnapshotSource, string> = {
  live: "Live sensor",
  manual: "Manual",
  sim: "Simulated",
  diary: "Diary snapshot",
  csv: "CSV history",
  unavailable: "Unavailable",
  unverified: "Unverified source",
};

/** Default stale threshold for live current-state (15 minutes). Prefer isSnapshotStale when source is known. */
export const STALE_THRESHOLD_MS = SENSOR_SNAPSHOT_STALE_THRESHOLD_MS;

export { isCurrentStateStale, LIVE_CURRENT_STATE_STALE_MS, resolveCurrentStateStaleWindowMs };

/**
 * Age-only stale check. Default threshold is the live window (15 minutes).
 * Pass `source` for Sensor Truth Canon source-aware windows (manual = 24h).
 * An explicit non-default `thresholdMs` always wins over source resolution.
 */
export function isStale(
  ts: string | null,
  now: number = Date.now(),
  thresholdMs: number = STALE_THRESHOLD_MS,
  source?: string | null,
): boolean {
  if (thresholdMs !== STALE_THRESHOLD_MS) {
    return isCurrentStateStale(ts, { now, thresholdMs });
  }
  if (source !== undefined) {
    return isCurrentStateStale(ts, { now, source });
  }
  return isCurrentStateStale(ts, { now, thresholdMs: STALE_THRESHOLD_MS });
}

/** Source-aware stale check for a snapshot that already carries provenance. */
export function isSnapshotStale(
  snapshot: Pick<SensorSnapshot, "ts" | "source">,
  now: number = Date.now(),
): boolean {
  return isCurrentStateStale(snapshot.ts, { now, source: snapshot.source });
}

export interface SensorReadingLike {
  ts: string;
  metric: string;
  value: number | string | null;
  source?: string | null;
  device_id?: string | null;
  /**
   * Originating `sensor_readings.id`. Optional: when present and the row
   * is selected as the contributing row for a known metric,
   * `snapshotFromReadings` populates `SensorSnapshot.metric_refs[<key>]`
   * for the env-alert ref population path. Never inferred.
   */
  id?: string | null;
  /**
   * Originating `sensor_readings.tent_id`. Used only to derive
   * {@link SensorSnapshot.tent_id} when every contributing row agrees.
   */
  tent_id?: string | null;
  /**
   * Upstream provenance envelope. This file NEVER reads, returns, or
   * renders its contents — it is forwarded as-is to
   * `summarizeCsvVendor`, which is the only sanctioned reader.
   */
  raw_payload?: unknown;
  /** Original capture time for imported/history rows; preferred over ts. */
  captured_at?: string | null;
}

/**
 * Map a {@link SensorSnapshotMetricRefKey} to the matching
 * `sensor_readings.metric` value. Snapshot fields and reading metrics
 * use different vocabularies; this table is the only mapping site.
 */
const METRIC_REF_KEY_TO_READING_METRIC: Record<SensorSnapshotMetricRefKey, string> = {
  temp: "temperature_c",
  rh: "humidity_pct",
  vpd: "vpd_kpa",
  soil: "soil_moisture_pct",
  soil_ec: "soil_ec",
  soil_temp: "soil_temp_c",
  ppfd: "ppfd",
};

/**
 * Build a snapshot from a batch of sensor_readings rows. Picks the latest
 * actual observation time (`captured_at` when present, otherwise `ts`) and
 * folds metric/value pairs at that time into the snapshot fields. Unknown
 * metrics are ignored, not faked.
 */
export function snapshotFromReadings(rows: SensorReadingLike[]): SensorSnapshot | null {
  if (!rows || rows.length === 0) return null;
  const observedRows = rows
    .map((row) => ({ row, observedAt: resolveSensorObservationTime(row) }))
    .filter(
      (item): item is { row: SensorReadingLike; observedAt: string } => item.observedAt !== null,
    );
  if (observedRows.length === 0) return null;
  const latestTs = observedRows.reduce(
    (latest, item) => (item.observedAt > latest ? item.observedAt : latest),
    observedRows[0].observedAt,
  );
  const latest = observedRows
    .filter((item) => item.observedAt === latestTs)
    .map((item) => item.row);
  const get = (metric: string): number | null => {
    const r = latest.find((x) => x.metric === metric);
    return r ? toFiniteNumber(r.value) : null;
  };
  const anyManual = latest.some((r) => r.source === "manual");
  // "demo" is the canonical name for simulated data in sensor_readings;
  // fold it into the card's existing "sim" bucket so demo rows can never
  // fall through to a live claim.
  const allSim =
    latest.length > 0 && latest.every((r) => r.source === "sim" || r.source === "demo");
  const allCsv = latest.length > 0 && latest.every((r) => r.source === "csv");
  const anyCsv = latest.some((r) => r.source === "csv");
  // "Live sensor" is a claim, not a default: it requires EVERY row at the
  // latest timestamp to carry a source in the live reservation. That
  // reservation is exactly {"live", "pi_bridge"} — the Pi bridge is the
  // first-party live-ingest path and its inclusion is pinned by
  // manual-sensor-snapshot-v1-audit ("reserved for pi_bridge/live rows
  // only"). Everything else — raw vendor strings like "ecowitt",
  // canonical "stale"/"invalid", or unexpected junk — classifies as
  // "unverified"; the strict trust-badge path refuses the same
  // promotion, and this card must not be looser than it.
  const allLive =
    latest.length > 0 &&
    latest.every((r) => isVerifiedSnapshotLiveRowSource(r.source) && !isSensorTestbenchRow(r));
  // CSV history must never be promoted to "live". If every row at the
  // latest timestamp is CSV, classify as "csv". If CSV is mixed with
  // non-live sources but no manual, still prefer csv over live so
  // imported history never masquerades as a live reading.
  const source: SnapshotSource = anyManual
    ? "manual"
    : allSim
      ? "sim"
      : allCsv
        ? "csv"
        : anyCsv
          ? "csv"
          : allLive
            ? "live"
            : "unverified";
  // Prefer a device_id from a row matching the resolved source so manual
  // device notes (device_id = "manual:...") are surfaced for manual
  // snapshots; otherwise fall back to any device_id at the latest ts.
  const deviceRow =
    latest.find((r) => r.source === source && !!r.device_id) ?? latest.find((r) => !!r.device_id);
  // Summarise CSV vendor lineage (presentation hint only — never
  // upgrades the source classification).
  const csvVendor = source === "csv" ? summarizeCsvVendor(latest) : null;
  // Per-metric provenance — use the EXACT row selected by `get(metric)`
  // (first match in `latest`, preserving existing selection semantics).
  // Only emit a ref when the row carries a non-empty id. Never inferred.
  let metric_refs: Partial<Record<SensorSnapshotMetricRefKey, SensorSnapshotMetricRef>> | undefined;
  for (const key of Object.keys(METRIC_REF_KEY_TO_READING_METRIC) as SensorSnapshotMetricRefKey[]) {
    const readingMetric = METRIC_REF_KEY_TO_READING_METRIC[key];
    const row = latest.find((x) => x.metric === readingMetric);
    if (!row) continue;
    const id = typeof row.id === "string" ? row.id.trim() : "";
    if (!id) continue;
    if (!metric_refs) metric_refs = {};
    metric_refs[key] = {
      id,
      captured_at: resolveSensorObservationTime(row) ?? latestTs,
      source: typeof row.source === "string" ? row.source : "",
    };
  }
  // Attribute a tent ONLY when every contributing row agrees on one.
  // Derived from `latest` — the exact rows this snapshot is built from —
  // so the tent can never describe evidence that did not produce it.
  // Mixed tents (e.g. the Dashboard's "All tents" view) yield null rather
  // than an arbitrary winner.
  // EVERY contributing row must carry the SAME non-blank tent. Filtering
  // blanks out before testing uniqueness would make ["tent-a", null] look
  // unanimous and pin the alert on tent-a, even though one contributing row
  // had no known tent — the precise mis-attribution this guard exists to
  // prevent. An unknown tent is disagreement, not absence.
  const latestTentIds = latest.map((r) => (typeof r.tent_id === "string" ? r.tent_id.trim() : ""));
  const tent_id =
    latestTentIds.length > 0 &&
    latestTentIds.every((id) => id.length > 0 && id === latestTentIds[0])
      ? latestTentIds[0]
      : null;
  return {
    source,
    ts: latestTs,
    temp: get("temperature_c"),
    rh: get("humidity_pct"),
    vpd: get("vpd_kpa"),
    co2: get("co2_ppm"),
    soil: get("soil_moisture_pct"),
    soil_ec: get("soil_ec"),
    soil_temp: get("soil_temp_c"),
    ppfd: get("ppfd"),
    device_id: deviceRow?.device_id ?? null,
    csvVendor,
    tent_id,
    ...(metric_refs ? { metric_refs } : {}),
  };
}

/**
 * Build a snapshot from a diary_entries.details.sensor_snapshot blob.
 *
 * Tolerates BOTH shapes:
 *   1. Legacy flat shape: { ts, temp, rh, vpd, co2, soil, soil_ec,
 *      soil_temp, ppfd } — written by pre-Quick-Log diary code. Numeric
 *      strings are coerced (existing contract).
 *   2. Quick Log v1 companion shape: { source, captured_at, metrics: {
 *      temperature, humidity, vpd, co2, soil_moisture, soil_temp,
 *      soil_ec, ppfd, ... } } — written by `createQuickLogEvent` into
 *      the companion diary row. Routed through the shared
 *      `normalizeQuickLogSnapshotMetrics` so legacy (`temperature_c`,
 *      `humidity_pct`, …) and clean canonical keys collapse to the
 *      same canonical vocabulary the Quick Log timeline / AI Doctor
 *      adapter consume. Without this, Quick Log writes render correctly
 *      in the timeline but "Unknown" in the Latest Environment card.
 *
 * Source label remains `"diary"` in both shapes so existing source-label
 * / trust badge behavior is preserved (no legacy/companion blob ever
 * relabels itself as `live` via this path).
 */
export function snapshotFromDiary(
  entryAt: string | null,
  snap: Record<string, unknown> | null | undefined,
): SensorSnapshot | null {
  if (!snap || typeof snap !== "object") return null;

  const rawMetrics =
    snap.metrics && typeof snap.metrics === "object" && !Array.isArray(snap.metrics)
      ? (snap.metrics as Record<string, unknown>)
      : null;

  if (rawMetrics) {
    const capturedAt =
      (typeof snap.captured_at === "string" ? (snap.captured_at as string) : null) ??
      (typeof snap.ts === "string" ? (snap.ts as string) : null) ??
      entryAt;
    if (!capturedAt) return null;
    const m = normalizeQuickLogSnapshotMetrics(rawMetrics);
    return {
      source: "diary",
      ts: capturedAt,
      temp: toFiniteNumber(m.temperature),
      rh: toFiniteNumber(m.humidity),
      vpd: toFiniteNumber(m.vpd),
      co2: toFiniteNumber(m.co2),
      soil: toFiniteNumber(m.soil_moisture),
      soil_ec: toFiniteNumber(m.soil_ec),
      soil_temp: toFiniteNumber(m.soil_temp),
      ppfd: toFiniteNumber(m.ppfd),
      device_id: null,
    };
  }

  const ts = (typeof snap.ts === "string" ? snap.ts : null) ?? entryAt;
  if (!ts) return null;
  return {
    source: "diary",
    ts,
    temp: toFiniteNumber(snap.temp),
    rh: toFiniteNumber(snap.rh),
    vpd: toFiniteNumber(snap.vpd),
    co2: toFiniteNumber(snap.co2),
    soil: toFiniteNumber(snap.soil),
    soil_ec: toFiniteNumber(snap.soil_ec),
    soil_temp: toFiniteNumber(snap.soil_temp),
    ppfd: toFiniteNumber(snap.ppfd),
    device_id: null,
  };
}

/**
 * Build a snapshot from a diary_entries.details.environment_check envelope
 * (Quick Log Environment Check, either variant — see #596).
 *
 * Contract decisions, made deliberately:
 *  - `source` is `"manual"`: an environment check is a grower-entered manual
 *    reading, the same trust class as a manual sensor snapshot, so it may
 *    feed alert evaluation. This does NOT weaken the diary fence —
 *    `snapshotFromDiary` blobs stay `"diary"` and stay non-persistable.
 *  - `ts` is the diary row's `entry_at` (== grow_events.occurred_at, the
 *    grower-reported observation time). The envelope itself carries no
 *    timestamp; using `logged_at` would make a back-dated check look fresh.
 *  - Only the three air metrics map (`temp_c`→temp, `humidity_pct`→rh,
 *    `vpd_kpa`→vpd). `water_temp_c` is reservoir temperature, NOT soil/root
 *    probe temperature, and `ec_mscm`'s soil-vs-reservoir identity is
 *    unresolved — neither is silently equated to a snapshot field.
 *  - A note-only envelope (all metrics null) is not sensor evidence → null.
 *  - Read-time distrust (Codex review, PR #601): diary JSON can be legacy or
 *    hand-written, so the write-time band gate cannot be assumed. Values are
 *    accepted only as number-typed finite values inside the same canonical
 *    plausibility bands the writer uses; `""`/booleans/numeric strings are
 *    rejected, never coerced, and an out-of-band metric drops to null.
 *  - When `diaryEntryId` is provided, the snapshot carries
 *    `diary_evidence_ref` so alert persistence can link the EXACT diary
 *    row (see #603). Never populates `metric_refs` (those are for
 *    `sensor_readings` rows only).
 */
function strictBandValue(value: unknown, isValid: (n: number | null) => boolean): number | null {
  if (typeof value !== "number" || !Number.isFinite(value)) return null;
  return isValid(value) ? value : null;
}

export interface SnapshotFromEnvironmentCheckOptions {
  /** Exact `diary_entries.id` for the row this envelope came from. */
  diaryEntryId?: string | null;
}

function buildDiaryEvidenceRef(
  entryAt: string,
  diaryEntryId: string | null | undefined,
): SensorSnapshotDiaryEvidenceRef | undefined {
  const diaryId = typeof diaryEntryId === "string" ? diaryEntryId.trim() : "";
  return diaryId
    ? ({ id: diaryId, entry_at: entryAt } satisfies SensorSnapshotDiaryEvidenceRef)
    : undefined;
}

export function snapshotFromEnvironmentCheck(
  entryAt: string | null,
  envCheck: Record<string, unknown> | null | undefined,
  options?: SnapshotFromEnvironmentCheckOptions | null,
): SensorSnapshot | null {
  if (!envCheck || typeof envCheck !== "object") return null;
  if (!entryAt) return null;
  const temp = strictBandValue(envCheck.temp_c, isTemperatureValid);
  const rh = strictBandValue(envCheck.humidity_pct, isHumidityValid);
  const vpd = strictBandValue(envCheck.vpd_kpa, isVpdValid);
  if (temp === null && rh === null && vpd === null) return null;

  const diary_evidence_ref = buildDiaryEvidenceRef(entryAt, options?.diaryEntryId);

  return {
    source: "manual",
    ts: entryAt,
    temp,
    rh,
    vpd,
    co2: null,
    soil: null,
    soil_ec: null,
    soil_temp: null,
    ppfd: null,
    device_id: null,
    ...(diary_evidence_ref ? { diary_evidence_ref } : {}),
  };
}

/**
 * Build a current-state snapshot from Plant Quick Log's persisted
 * `details.manual_sensor_snapshot` payload.
 *
 * The Quick Log payload is diary evidence, not a `sensor_readings` row:
 *
 * - Requires the literal `source: "manual"`; it never upgrades a diary blob
 *   to live telemetry.
 * - Maps only the fields the current SensorSnapshot contract understands:
 *   `temp_f` -> canonical Celsius `temp` and `humidity_percent` -> `rh`.
 *   pH / EC stay in the diary record because SensorSnapshot has no equivalent
 *   fields; VPD is not derived here.
 * - Requires number-typed, finite persisted values and drops out-of-band
 *   temperature / humidity values. An all-missing or invalid payload returns
 *   null, so it cannot masquerade as current sensor truth.
 * - Carries the exact diary entry id when available; it never fabricates a
 *   sensor_readings metric ref.
 */
export function snapshotFromManualSensorSnapshot(
  entryAt: string | null,
  manualSnapshot: Record<string, unknown> | null | undefined,
  options?: SnapshotFromEnvironmentCheckOptions | null,
): SensorSnapshot | null {
  if (!manualSnapshot || typeof manualSnapshot !== "object") return null;
  if (typeof entryAt !== "string" || !Number.isFinite(Date.parse(entryAt))) return null;
  if (manualSnapshot.source !== "manual") return null;

  const rawTempF = manualSnapshot.temp_f;
  const tempF = typeof rawTempF === "number" && Number.isFinite(rawTempF) ? rawTempF : null;
  const convertedTemp = tempF === null ? null : fahrenheitToCelsius(tempF);
  const temp = convertedTemp !== null && isTemperatureValid(convertedTemp) ? convertedTemp : null;
  const rh = strictBandValue(manualSnapshot.humidity_percent, isHumidityValid);

  if (temp === null && rh === null) return null;

  const diary_evidence_ref = buildDiaryEvidenceRef(entryAt, options?.diaryEntryId);
  return {
    source: "manual",
    alert_persistence_eligible: false,
    ts: entryAt,
    temp,
    rh,
    vpd: null,
    co2: null,
    soil: null,
    soil_ec: null,
    soil_temp: null,
    ppfd: null,
    device_id: null,
    ...(diary_evidence_ref ? { diary_evidence_ref } : {}),
  };
}

export function formatValue(v: number | null, unit: string, digits = 1): string {
  if (v === null) return "Unknown";
  return `${v.toFixed(digits)}${unit}`;
}
