// @generated by scripts/sync-edge-shared.mjs — DO NOT EDIT.
// Source: src/lib/timelineEntryAnchorRules.ts
// sha256: 069dc7a085d0ad025f59ed3799778df442c329df3baf340e668babfb52d8d8ae
// To regenerate: bun run sync-edge-shared

/**
 * Pure rules for Timeline entry anchors and Quick Log companion aliases.
 *
 * Diary mirror rows have their own ids, while save RPCs return the linked
 * grow_events id. A secondary alias lets a post-save handoff address the
 * visible diary row without guessing by timestamp or exposing any private
 * payload fields.
 */

const SAFE_ENTRY_ID = /^[A-Za-z0-9_-]{1,200}$/;

function safeEntryId(value: unknown): string | null {
  if (typeof value !== "string") return null;
  const trimmed = value.trim();
  return SAFE_ENTRY_ID.test(trimmed) ? trimmed : null;
}

export function buildTimelineEntryAnchorId(entryId: unknown): string | null {
  const id = safeEntryId(entryId);
  return id ? `timeline-entry-${id}` : null;
}

export function buildLinkedGrowEventTimelineAnchorId(details: unknown): string | null {
  if (!details || typeof details !== "object" || Array.isArray(details)) {
    return null;
  }
  const record = details as Record<string, unknown>;
  return (
    buildTimelineEntryAnchorId(record.linked_grow_event_id) ??
    buildTimelineEntryAnchorId(record.grow_event_id)
  );
}

/** Reserve only anchors for diary rows actually rendered after page/filter selection. */
export function buildRenderedDiaryTimelineAnchorIds(
  entries: readonly ({ id?: unknown; details?: unknown } | null | undefined)[] | null | undefined,
): ReadonlySet<string> {
  const anchors = new Set<string>();
  for (const entry of entries ?? []) {
    if (!entry) continue;
    const primary = buildTimelineEntryAnchorId(entry.id);
    if (!primary) continue;
    anchors.add(primary);
    const linked = buildLinkedGrowEventTimelineAnchorId(entry.details);
    if (linked) anchors.add(linked);
  }
  return anchors;
}

/** A typed history card owns the event fragment only when no rendered diary row does. */
export function resolveHistoryTimelineAnchorId(
  anchorId: string | null | undefined,
  reserved?: ReadonlySet<string> | null,
): string | null {
  return anchorId && !reserved?.has(anchorId) ? anchorId : null;
}
