#!/usr/bin/env node
/**
 * stamp-version.mjs
 *
 * Runs before every production build and stamps a single deterministic
 * version record derived from git + package.json + build-time inputs.
 * Writes to two locations so both server-side (build artifacts, CI
 * summary) and client-side (in-app diagnostics, /version.json probe)
 * consumers see the identical value:
 *
 *   1. public/version.json      — served verbatim as /version.json at
 *                                 runtime; safe for humans and uptime
 *                                 checks to pin against.
 *   2. src/generated/buildInfo.ts — typed export imported by any UI
 *                                 that shows "Version: X" (footer,
 *                                 About page, error boundaries).
 *
 * Version string format:
 *   <pkg.version>+<yyyymmdd>.<shortSha>[-dirty]
 * Example: `0.0.0+20260722.c76e2cd37929`
 *
 * No secrets, env dumps, or PII. Everything written here is safe to
 * ship in the client bundle.
 */
import { execSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

function safe(fn, fallback = "unknown") {
  try {
    const v = fn();
    return v == null || v === "" ? fallback : v;
  } catch {
    return fallback;
  }
}

const pkg = JSON.parse(readFileSync(resolve("package.json"), "utf8"));
const pkgVersion = String(pkg.version ?? "0.0.0");

const sha = process.env.GITHUB_SHA ?? safe(() => execSync("git rev-parse HEAD").toString().trim());
const shortSha = sha === "unknown" ? "unknown" : sha.slice(0, 12);
const ref = process.env.GITHUB_REF_NAME ?? safe(() => execSync("git rev-parse --abbrev-ref HEAD").toString().trim());
const commitTime = safe(() => execSync(`git show -s --format=%cI ${sha === "unknown" ? "HEAD" : sha}`).toString().trim());

// Dirty flag: unstaged/uncommitted changes at build time. Never
// suppress — a dirty CI build is always a bug worth surfacing.
const dirty = safe(() => execSync("git status --porcelain").toString().trim(), "") !== "";

const buildTime = new Date().toISOString();
const yyyymmdd = buildTime.slice(0, 10).replace(/-/g, "");
const tag = process.env.GITHUB_REF_TYPE === "tag" ? process.env.GITHUB_REF_NAME : null;

const version = `${pkgVersion}+${yyyymmdd}.${shortSha}${dirty ? "-dirty" : ""}`;

const record = {
  version,
  packageVersion: pkgVersion,
  commit: sha,
  shortCommit: shortSha,
  ref,
  tag,
  commitTime,
  buildTime,
  dirty,
  ciRunId: process.env.GITHUB_RUN_ID ?? null,
  ciRunUrl:
    process.env.GITHUB_RUN_ID && process.env.GITHUB_SERVER_URL && process.env.GITHUB_REPOSITORY
      ? `${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}`
      : null,
};

// 1. public/version.json — served at /version.json
const publicPath = resolve("public/version.json");
mkdirSync(dirname(publicPath), { recursive: true });
writeFileSync(publicPath, JSON.stringify(record, null, 2) + "\n");

// 2. src/generated/buildInfo.ts — typed import for UI diagnostics
const tsPath = resolve("src/generated/buildInfo.ts");
mkdirSync(dirname(tsPath), { recursive: true });
const tsBody = `// AUTO-GENERATED by scripts/stamp-version.mjs — do not edit by hand.
// Regenerated on every \`bun run build\` (via the \`prebuild\` script).
// Safe to import from client code; contains no secrets.

export interface BuildInfo {
  readonly version: string;
  readonly packageVersion: string;
  readonly commit: string;
  readonly shortCommit: string;
  readonly ref: string;
  readonly tag: string | null;
  readonly commitTime: string;
  readonly buildTime: string;
  readonly dirty: boolean;
  readonly ciRunId: string | null;
  readonly ciRunUrl: string | null;
}

export const buildInfo: BuildInfo = ${JSON.stringify(record, null, 2)} as const;

export const APP_VERSION = buildInfo.version;
`;
writeFileSync(tsPath, tsBody);

console.log(`Stamped version ${version} → public/version.json, src/generated/buildInfo.ts`);
