// @generated by scripts/sync-edge-shared.mjs — DO NOT EDIT.
// Source: src/constants/sensorTiming.ts
// sha256: 50136073eaabfb1c4c8aa87e3cb4d83b3c47e4fdb0f2ffbaf7a320a18f93d238
// To regenerate: bun run sync-edge-shared

/**
 * sensorTiming — the single home for every sensor stale/freshness window.
 *
 * Consolidated by the 2026-07-30 sensor-truth slice (#592). The 2026-07-30
 * audit found these windows duplicated across 19 modules with SEVEN distinct
 * values while docs/data-labeling-spec.md §freshness specifies 15 minutes
 * for live readings. Per the slice's product decision, consolidation
 * PRESERVES each surface's current value — the divergence is now explicit
 * and named instead of scattered, and unifying any value is a deliberate
 * one-line follow-up here rather than a scavenger hunt.
 *
 * Rules:
 *  - One constant per consuming surface, named for that surface, unit suffix
 *    in the name (_MS / _MINUTES / _HOURS).
 *  - Mirrored edge modules import this file by its EXPLICIT path
 *    (`@/constants/sensorTiming`), never via the `@/constants` barrel — the
 *    edge-shared sync only rewrites explicit `@/constants/*` specifiers.
 *  - Do not add non-timing constants here.
 */

// ---------------------------------------------------------------------------
// 15 minutes — matches docs/data-labeling-spec.md for live-reading freshness.
// ---------------------------------------------------------------------------

/** Dashboard latest-snapshot freshness (latestSensorSnapshotRules). */
export const SENSOR_FRESH_WINDOW_MINUTES = 15;

/** Operator live-source truth gate (liveSourceTruthGateRules). */
export const LIVE_SOURCE_TRUTH_STALE_AFTER_MS = 15 * 60 * 1000;

/** EcoWitt live soil ingest acceptance (ecowittLiveSoilIngestRules). */
export const ECOWITT_LIVE_SOIL_STALE_MS = 15 * 60 * 1000;

/** EcoWitt MQTT ingest acceptance (ecowittMqttIngestRules). */
export const ECOWITT_MQTT_STALE_MS = 15 * 60 * 1000;

/** Grow data source label freshness (growDataSourceLabelRules). */
export const GROW_DATA_SOURCE_LABEL_STALE_MS = 15 * 60 * 1000;

/** Bridge troubleshooting "recent ingest" window (ecowittBridgeTroubleshootingRules). */
export const ECOWITT_BRIDGE_TROUBLESHOOTING_STALE_MS = 15 * 60 * 1000;

/** Testbench transport-receiving window (sensorTestbenchIndicatorRules, #584). */
export const SENSOR_TESTBENCH_LIVE_WINDOW_MS = 15 * 60 * 1000;

// ---------------------------------------------------------------------------
// 30 minutes — DIVERGES from the spec's 15; grower-visible on the dashboard
// card, alert persistence, and AI context. Unify deliberately, not here.
// ---------------------------------------------------------------------------

/** Dashboard snapshot + alert-persistence staleness (sensorSnapshot.isStale). */
export const SENSOR_SNAPSHOT_STALE_THRESHOLD_MS = 30 * 60 * 1000;

/** Reading normalization staleness (sensorReadingNormalizationRules). */
export const SENSOR_READING_NORMALIZATION_STALE_MS = 30 * 60 * 1000;

/** Source-health rollup staleness (sensorSourceHealthRules). */
export const SENSOR_SOURCE_STALE_MINUTES = 30;

/** AI Coach snapshot context staleness (aiCoachSensorSnapshotContext). */
export const DEFAULT_AI_COACH_STALE_THRESHOLD_MS = 30 * 60 * 1000;

/** AI Doctor sensor context staleness (aiSensorSnapshotContextRules). */
export const DEFAULT_AI_SENSOR_STALE_THRESHOLD_MS = 30 * 60 * 1000;

/** Grow Room Mode display staleness (growRoomModeRules). */
export const GROW_ROOM_MODE_STALE_MINUTES = 30;

// ---------------------------------------------------------------------------
// Longer windows — channel labeling, manual snapshots, status contract.
// ---------------------------------------------------------------------------

/** EcoWitt channel labeling recency (ecowittChannelLabelingRules). */
export const ECOWITT_CHANNEL_LABELING_STALE_AFTER_MS = 60 * 60 * 1000;

/** Manual snapshot "current" window — 6h (manualSensorSnapshotQualityRules).
 *  NOTE: docs/data-labeling-spec.md says 24h for manual; divergence tracked
 *  in #592. */
export const MANUAL_SNAPSHOT_CURRENT_STALE_HOURS = 6;

/** AI context sufficiency sensor staleness — 6h (aiContextSufficiencyRules). */
export const DEFAULT_SENSOR_STALE_MS = 6 * 60 * 60 * 1000;

/** Snapshot status contract default window — 24h (sensorSnapshotStatusContract). */
export const DEFAULT_STALE_WINDOW_MS = 24 * 60 * 60 * 1000;

/** EcoWitt ingest validation view recency — 24h (ecowittIngestValidationViewModel). */
export const ECOWITT_INGEST_VALIDATION_STALE_AFTER_MS = 24 * 60 * 60 * 1000;

/** No-recent-log recovery nudge — 72h (noRecentLogRecoveryRules). */
export const NO_RECENT_LOG_STALE_AFTER_HOURS = 72;
