// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-grows.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/tools/_supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.4";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const anon = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  if (!url || !anon) {
    throw new Error("Supabase env not configured for MCP tool");
  }
  return createClient(url, anon, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function unauthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated." }],
    isError: true
  };
}

// src/lib/mcp/tools/list-grows.ts
var list_grows_default = defineTool({
  name: "list_grows",
  title: "List grows",
  description: "List the signed-in Verdant grower's own grows (id, name, stage, grow_type, archived flag, timestamps). Read-only.",
  inputSchema: {
    includeArchived: z.boolean().optional().describe("Include archived grows. Defaults to false."),
    limit: z.number().int().min(1).max(100).optional().describe("Maximum rows to return (1\u2013100). Defaults to 25.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ includeArchived, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("grows").select("id,name,stage,grow_type,is_archived,started_at,created_at,updated_at").order("updated_at", { ascending: false }).limit(limit ?? 25);
    if (!includeArchived) query = query.eq("is_archived", false);
    const { data, error } = await query;
    if (error) {
      return {
        content: [{ type: "text", text: `Error: ${error.message}` }],
        isError: true
      };
    }
    const rows = data ?? [];
    return {
      content: [
        {
          type: "text",
          text: rows.length === 0 ? "No grows found." : `Found ${rows.length} grow(s):
${JSON.stringify(rows, null, 2)}`
        }
      ],
      structuredContent: { grows: rows }
    };
  }
});

// src/lib/mcp/tools/list-recent-diary-entries.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var list_recent_diary_entries_default = defineTool2({
  name: "list_recent_diary_entries",
  title: "List recent diary entries",
  description: "List recent diary entries for one of the signed-in grower's grows. Read-only.",
  inputSchema: {
    growId: z2.string().uuid().describe("Grow id to fetch diary entries for."),
    limit: z2.number().int().min(1).max(50).optional().describe("Maximum entries to return (1\u201350). Defaults to 10.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ growId, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("diary_entries").select("id,grow_id,plant_id,tent_id,event_type,note,created_at").eq("grow_id", growId).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (error) {
      return {
        content: [{ type: "text", text: `Error: ${error.message}` }],
        isError: true
      };
    }
    const rows = data ?? [];
    return {
      content: [
        {
          type: "text",
          text: rows.length === 0 ? "No diary entries found for that grow." : `Found ${rows.length} entry(ies):
${JSON.stringify(rows, null, 2)}`
        }
      ],
      structuredContent: { entries: rows }
    };
  }
});

// src/lib/mcp/tools/get-latest-sensor-snapshot.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
var get_latest_sensor_snapshot_default = defineTool3({
  name: "get_latest_sensor_snapshot",
  title: "Get latest sensor snapshot",
  description: "Fetch the single most recent sensor reading for one of the signed-in grower's tents. Includes temperature/humidity/vpd/co2 fields when present and always includes the `source` label (live/manual/csv/demo/stale/invalid). Never treat non-live sources as current readings. Read-only.",
  inputSchema: {
    tentId: z3.string().uuid().describe("Tent id to fetch the latest reading for.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ tentId }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("sensor_readings").select(
      "id,tent_id,plant_id,source,captured_at,temperature_c,humidity_pct,vpd_kpa,co2_ppm,soil_moisture_pct,ph,ec_ms_cm,confidence"
    ).eq("tent_id", tentId).order("captured_at", { ascending: false }).limit(1).maybeSingle();
    if (error) {
      return {
        content: [{ type: "text", text: `Error: ${error.message}` }],
        isError: true
      };
    }
    if (!data) {
      return {
        content: [{ type: "text", text: "No sensor snapshot found for that tent." }],
        structuredContent: { snapshot: null }
      };
    }
    return {
      content: [
        {
          type: "text",
          text: `Latest reading (source: ${data.source}):
${JSON.stringify(data, null, 2)}`
        }
      ],
      structuredContent: { snapshot: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "knkwiiywfkbqznbxwqfh";
var mcp_default = defineMcp({
  name: "verdant-grow-os-mcp",
  title: "Verdant Grow OS",
  version: "0.1.0",
  instructions: "Read-only access to the signed-in Verdant grower's own data. Use `list_grows` to enumerate grows, `list_recent_diary_entries` for recent log entries in a grow, and `get_latest_sensor_snapshot` to read the most recent sensor reading for a tent. Sensor rows always include their `source` label (live/manual/csv/demo/stale/invalid) \u2014 never treat non-live sources as current readings. This server never writes, never approves Action Queue items, and never controls devices.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_grows_default,
    list_recent_diary_entries_default,
    get_latest_sensor_snapshot_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
