-- Duplicate retired.
--
-- The canonical AI credit grant ledger migration is:
--   20260721103000_ai_credit_grants.sql
--
-- This later Lovable-timestamp migration carried the same table/function
-- definitions and caused local Supabase resets to fail with:
--   relation "ai_credit_grants" already exists
--
-- Keep the migration version present for environments that may have recorded it,
-- but make fresh resets idempotent by leaving the real definition to the
-- canonical, earlier migration.
SELECT 1;
