-- DISABLED: this migration previously attempted a fabricated tent restore.
--
-- See docs/database-integrity-incident-runbook.md
--
-- The original SQL inserted a placeholder row into public.tents using a
-- hardcoded grow_id to "resolve" orphan tent_id references. That pattern
-- repeatedly failed with tents_grow_id_fkey because the referenced grow
-- row no longer existed, and -- more importantly -- fabricating
-- grow/tent rows to satisfy FK errors destroys forensic evidence of real
-- data loss and is forbidden by Verdant's database integrity policy.
--
-- This file is intentionally retained (rather than deleted) so the
-- migration name stays in the applied-migrations history and is never
-- re-run with the old, unsafe body. Do NOT replace this with another
-- INSERT-based "repair". Real data loss must be recovered from Supabase
-- backup / PITR, not from hand-written rows.
--
-- Static guardrail: src/test/database-integrity-incident-guardrails.test.ts
SELECT 1 WHERE false;
