// This file is automatically generated. Do not edit it directly.
// MINIMAL HARDENING EDIT: the auth storage below intentionally uses a
// sessionStorage-backed adapter that falls back only to page memory when a
// browser blocks storage. See docs/auth-security.md for tradeoffs. Do not
// regenerate this file without preserving that auth storage hardening.
import { createClient } from "@supabase/supabase-js";
import { resilientSessionStorage } from "@/lib/resilientSessionStorage";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: resilientSessionStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
