/**
 * Hand-maintained typed boundary for the Genetics & Propagation Traceability
 * tables and RPCs.
 *
 * WHY THIS FILE EXISTS (same rationale as phenoTables.ts): the generated
 * `types.ts` is regenerated by Lovable and lags migrations, dropping these
 * tables. Hand-edits to `types.ts` are reverted on regeneration, so the
 * genetics traceability code accesses its tables/RPCs through this narrow,
 * hand-maintained boundary instead. Scope is types-only — no schema, RLS, or
 * runtime-behavior change. It re-types the SAME runtime supabase client; only
 * the Database generic is swapped (no `any`, no `ts-ignore` downstream).
 *
 * Append-only tables declare `Update = never` so `.update()` fails at compile
 * time — a second gate behind the DB's append-only grants. All writes should go
 * through the typed RPCs below, not `.from().insert()`.
 */
import type { SupabaseClient } from "@supabase/supabase-js";
import { supabase } from "./client";
import type { Json } from "./types";

// DB-defaulted / nullable columns become Partial on Insert.
type WithDefaults<Row, Defaulted extends keyof Row> = Omit<Row, Defaulted> &
  Partial<Pick<Row, Defaulted>>;

interface Tbl<
  Row extends Record<string, unknown>,
  Defaulted extends keyof Row,
  Update = Partial<Row>,
> {
  Row: Row;
  Insert: WithDefaults<Row, Defaulted>;
  Update: Update;
  Relationships: [];
}

// ---------------------------------------------------------------------------
// Row types (snake_case, mirroring the SQL). Nullable columns are `T | null`.
// ---------------------------------------------------------------------------
type GeneticsAccessionRow = {
  id: string;
  user_id: string;
  source_kind: string;
  source_party: string | null;
  cultivar_name: string | null;
  line_name: string | null;
  selection_id: string | null;
  generation: string | null;
  acquisition_date: string | null;
  known_state: string;
  linked_keeper_id: string | null;
  linked_clone_id: string | null;
  linked_cross_id: string | null;
  linked_plant_id: string | null;
  notes: string | null;
  archived_at: string | null;
  created_at: string;
  updated_at: string;
};

type GeneticsMutationIdempotencyRow = {
  user_id: string;
  operation: string;
  idempotency_key: string;
  request_hash: string;
  result: Json;
  created_at: string;
};

type PropagationBatchRow = {
  id: string;
  user_id: string;
  batch_code: string;
  name: string | null;
  propagation_method: string;
  source_accession_id: string | null;
  mother_plant_id: string | null;
  origin_unknown: boolean;
  cut_date: string | null;
  received_date: string | null;
  started_date: string | null;
  rooted_date: string | null;
  initial_quantity: number | null;
  viable_quantity: number | null;
  counts_unknown: boolean;
  status: string;
  grow_id: string | null;
  tent_id: string | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
};

type PropagationBatchStatusEventRow = {
  id: string;
  user_id: string;
  batch_id: string;
  from_status: string | null;
  to_status: string;
  reason: string | null;
  changed_at: string;
  created_at: string;
};

type PlantOriginAssignmentRow = {
  id: string;
  user_id: string;
  plant_id: string;
  batch_id: string;
  assigned_at: string;
  assigned_reason: string | null;
  created_at: string;
  updated_at: string;
};

type PlantOriginAssignmentEventRow = {
  id: string;
  user_id: string;
  plant_id: string;
  from_batch_id: string | null;
  to_batch_id: string;
  reason: string | null;
  action: string;
  changed_at: string;
  created_at: string;
};

type GeneticsScreeningResultRow = {
  id: string;
  user_id: string;
  subject_type: string;
  subject_id: string;
  target: string;
  result: string;
  sample_reference: string | null;
  laboratory: string | null;
  collected_date: string | null;
  result_date: string | null;
  evidence_reference: string | null;
  supersedes_id: string | null;
  recorded_by: string;
  recorded_at: string;
  created_at: string;
};

type QuarantineEpisodeRow = {
  id: string;
  user_id: string;
  subject_type: string;
  subject_id: string;
  target: string;
  status: string;
  opened_at: string;
  opened_reason: string | null;
  reopened_at: string | null;
  closed_at: string | null;
  closure_kind: string | null;
  closure_screening_result_id: string | null;
  created_at: string;
  updated_at: string;
};

type QuarantineTransitionEventRow = {
  id: string;
  user_id: string;
  episode_id: string;
  action: string;
  reason: string | null;
  screening_result_id: string | null;
  is_override: boolean;
  changed_at: string;
  created_at: string;
};

// ---------------------------------------------------------------------------
// Function (RPC) argument + return types. Returns are the jsonb envelope (Json).
// ---------------------------------------------------------------------------
interface GeneticsFn<Args> {
  Args: Args;
  Returns: Json;
}

export interface GeneticsTraceabilityDatabase {
  public: {
    Tables: {
      genetics_accessions: Tbl<
        GeneticsAccessionRow,
        | "id"
        | "source_kind"
        | "source_party"
        | "cultivar_name"
        | "line_name"
        | "selection_id"
        | "generation"
        | "acquisition_date"
        | "known_state"
        | "linked_keeper_id"
        | "linked_clone_id"
        | "linked_cross_id"
        | "linked_plant_id"
        | "notes"
        | "archived_at"
        | "created_at"
        | "updated_at"
      >;
      // Idempotency ledger is written only by SECURITY DEFINER RPCs; never
      // insert/update it from the client.
      genetics_mutation_idempotency: Tbl<
        GeneticsMutationIdempotencyRow,
        "created_at",
        never
      >;
      propagation_batches: Tbl<
        PropagationBatchRow,
        | "id"
        | "name"
        | "propagation_method"
        | "source_accession_id"
        | "mother_plant_id"
        | "origin_unknown"
        | "cut_date"
        | "received_date"
        | "started_date"
        | "rooted_date"
        | "initial_quantity"
        | "viable_quantity"
        | "counts_unknown"
        | "status"
        | "grow_id"
        | "tent_id"
        | "notes"
        | "created_at"
        | "updated_at"
      >;
      // Append-only status history — Update = never.
      propagation_batch_status_events: Tbl<
        PropagationBatchStatusEventRow,
        "id" | "from_status" | "reason" | "changed_at" | "created_at",
        never
      >;
      plant_origin_assignments: Tbl<
        PlantOriginAssignmentRow,
        "id" | "assigned_at" | "assigned_reason" | "created_at" | "updated_at"
      >;
      // Append-only assignment audit — Update = never.
      plant_origin_assignment_events: Tbl<
        PlantOriginAssignmentEventRow,
        "id" | "from_batch_id" | "reason" | "changed_at" | "created_at",
        never
      >;
      // Append-only screening evidence ledger — Update = never.
      genetics_screening_results: Tbl<
        GeneticsScreeningResultRow,
        | "id"
        | "sample_reference"
        | "laboratory"
        | "collected_date"
        | "result_date"
        | "evidence_reference"
        | "supersedes_id"
        | "recorded_at"
        | "created_at",
        never
      >;
      quarantine_episodes: Tbl<
        QuarantineEpisodeRow,
        | "id"
        | "status"
        | "opened_at"
        | "opened_reason"
        | "reopened_at"
        | "closed_at"
        | "closure_kind"
        | "closure_screening_result_id"
        | "created_at"
        | "updated_at"
      >;
      // Append-only transition history — Update = never.
      quarantine_transition_events: Tbl<
        QuarantineTransitionEventRow,
        "id" | "reason" | "screening_result_id" | "is_override" | "changed_at" | "created_at",
        never
      >;
    };
    Views: Record<string, never>;
    Functions: {
      genetics_accession_upsert: GeneticsFn<{
        p_idempotency_key: string;
        p_payload: Json;
      }>;
      genetics_accession_archive: GeneticsFn<{
        p_idempotency_key: string;
        p_accession_id: string;
        p_archived: boolean;
      }>;
      genetics_batch_upsert: GeneticsFn<{
        p_idempotency_key: string;
        p_payload: Json;
      }>;
      genetics_assign_plants: GeneticsFn<{
        p_idempotency_key: string;
        p_batch_id: string;
        p_plant_ids: string[];
        p_reason?: string | null;
      }>;
      genetics_screening_record: GeneticsFn<{
        p_idempotency_key: string;
        p_payload: Json;
      }>;
      genetics_quarantine_open: GeneticsFn<{
        p_idempotency_key: string;
        p_payload: Json;
      }>;
      genetics_quarantine_transition: GeneticsFn<{
        p_idempotency_key: string;
        p_episode_id: string;
        p_action: string;
        p_reason?: string | null;
        p_screening_result_id?: string | null;
      }>;
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}

/**
 * The one sanctioned cast: re-types the SAME runtime client (auth/fetch/instance
 * untouched); only the Database generic differs. Use this for genetics table
 * reads and RPC writes.
 */
export const geneticsTraceabilityDb =
  supabase as unknown as SupabaseClient<GeneticsTraceabilityDatabase>;
