/**
 * Hand-maintained typed boundary for the Genetics & Propagation Traceability
 * tables and RPCs.
 *
 * WHY THIS FILE EXISTS (same rationale as phenoTables.ts): the generated
 * `types.ts` is regenerated by Lovable and lags migrations, dropping these
 * tables. Hand-edits to `types.ts` are reverted on regeneration, so the
 * genetics traceability code accesses its tables/RPCs through this narrow,
 * hand-maintained boundary instead. Scope is types-only — no schema, RLS, or
 * runtime-behavior change. It re-types the SAME runtime supabase client; only
 * the Database generic is swapped (no `any`, no `ts-ignore` downstream).
 *
 * Append-only tables declare `Update = never` so `.update()` fails at compile
 * time — a second gate behind the DB's append-only grants. All writes should go
 * through the typed RPCs below, not `.from().insert()`.
 */
import type { SupabaseClient } from "@supabase/supabase-js";
import { supabase } from "./client";
import type { Json } from "./types";

// DB-defaulted / nullable columns become Partial on Insert.
type WithDefaults<Row, Defaulted extends keyof Row> = Omit<Row, Defaulted> &
  Partial<Pick<Row, Defaulted>>;

interface Tbl<
  Row extends Record<string, unknown>,
  Defaulted extends keyof Row,
  Update = Partial<Row>,
> {
  Row: Row;
  Insert: WithDefaults<Row, Defaulted>;
  Update: Update;
  Relationships: [];
}

// ---------------------------------------------------------------------------
// Row types (snake_case, mirroring the SQL). Nullable columns are `T | null`.
// ---------------------------------------------------------------------------
type GeneticsAccessionRow = {
  id: string;
  user_id: string;
  source_kind: string;
  source_party: string | null;
  cultivar_name: string | null;
  line_name: string | null;
  selection_id: string | null;
  generation: string | null;
  acquisition_date: string | null;
  known_state: string;
  linked_keeper_id: string | null;
  linked_clone_id: string | null;
  linked_cross_id: string | null;
  linked_plant_id: string | null;
  notes: string | null;
  archived_at: string | null;
  created_at: string;
  updated_at: string;
};

type GeneticsMutationIdempotencyRow = {
  user_id: string;
  operation: string;
  idempotency_key: string;
  request_hash: string;
  result: Json;
  created_at: string;
};

// ---------------------------------------------------------------------------
// Function (RPC) argument + return types. Returns are the jsonb envelope (Json).
// ---------------------------------------------------------------------------
interface GeneticsFn<Args> {
  Args: Args;
  Returns: Json;
}

export interface GeneticsTraceabilityDatabase {
  public: {
    Tables: {
      genetics_accessions: Tbl<
        GeneticsAccessionRow,
        | "id"
        | "source_kind"
        | "source_party"
        | "cultivar_name"
        | "line_name"
        | "selection_id"
        | "generation"
        | "acquisition_date"
        | "known_state"
        | "linked_keeper_id"
        | "linked_clone_id"
        | "linked_cross_id"
        | "linked_plant_id"
        | "notes"
        | "archived_at"
        | "created_at"
        | "updated_at"
      >;
      // Idempotency ledger is written only by SECURITY DEFINER RPCs; never
      // insert/update it from the client.
      genetics_mutation_idempotency: Tbl<
        GeneticsMutationIdempotencyRow,
        "created_at",
        never
      >;
    };
    Views: Record<string, never>;
    Functions: {
      genetics_accession_upsert: GeneticsFn<{
        p_idempotency_key: string;
        p_payload: Json;
      }>;
      genetics_accession_archive: GeneticsFn<{
        p_idempotency_key: string;
        p_accession_id: string;
        p_archived: boolean;
      }>;
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}

/**
 * The one sanctioned cast: re-types the SAME runtime client (auth/fetch/instance
 * untouched); only the Database generic differs. Use this for genetics table
 * reads and RPC writes.
 */
export const geneticsTraceabilityDb =
  supabase as unknown as SupabaseClient<GeneticsTraceabilityDatabase>;
