// @generated by scripts/sync-edge-shared.mjs — DO NOT EDIT.
// Source: src/lib/cost/index.ts
// sha256: 092f062d4b8d4bae292d1dc6d62007ac47df5723fc04227230969e0e714e9d00
// To regenerate: bun run sync-edge-shared

/**
 * Verdant cost library public entrypoint.
 *
 * Minimal, intentional surface: stable measurement types, the AI Doctor
 * prompt measurement builder, and the provider-response measurement composer.
 *
 * Hard constraints (measurement-only):
 *  - Pure: no I/O, no Supabase, no fetch, no model calls, no React, no
 *    browser APIs, no timers.
 *  - No persistence wiring is exported here.
 *  - No raw extractor/normalizer helpers are re-exported — those remain
 *    internal building blocks behind the composer boundary.
 *  - No budgets, thresholds, back-pressure, alerts, or device control.
 */

export {
  type AiDoctorPromptMeasurement,
  type WindowRefreshMeasurement,
  type IngestRateMeasurement,
  type RawHistoryFallbackState,
  type MeasurementStatus,
  type CostDomain,
} from "./costDomains.ts";

export {
  buildAiDoctorPromptMeasurement,
  classifyRawHistoryFallback,
  type AiDoctorPromptMeasurementBundle,
  type AiDoctorPromptMeasurementMetadata,
  type BuildAiDoctorPromptMeasurementInput,
  type ProviderReportedTokenUsage,
} from "./aiDoctorPromptMeasurement.ts";

export { attachProviderResponseUsageToAiDoctorPromptMeasurement } from "./aiDoctorProviderResponseMeasurementComposer.ts";
