/**
 * MCP local RLS harness — operational helpers.
 *
 * Three pure/test-only concerns live here so the integration harness,
 * its always-run unit tests, and CI share one implementation:
 *
 * 1. Artifact sanitizer — redacts token/secret-like values (JWTs, bearer
 *    strings, service_role, refresh/bridge/access tokens, client secrets,
 *    raw headers, raw_payload, and live env values) from anything the
 *    harness persists for CI debugging.
 * 2. Failure-artifact writer — writes sanitized JSON/log files under
 *    `artifacts/mcp-local-rls/` (override with MCP_RLS_ARTIFACT_DIR).
 *    CI uploads that directory only when the job fails.
 * 3. Manifest-driven RLS case derivation — reads the advertised MCP tool
 *    input schemas and generates pagination/filter isolation cases for
 *    exactly the params each tool advertises. Params are never invented:
 *    unclassified properties generate nothing.
 *
 * SAFETY: test/ops tooling only. No product, schema, RLS, Edge Function,
 * auth, or MCP tool behavior changes belong in this file.
 */
import * as fs from "node:fs";
import * as path from "node:path";

// ---------------------------------------------------------------------------
// 1. Sanitizer
// ---------------------------------------------------------------------------

export const REDACTED = "[REDACTED]";

/** Text-level patterns that must never survive into an artifact. */
export const SECRET_TEXT_RULES: Array<{ label: string; re: RegExp }> = [
  // JWT-like triplets (header.payload.signature).
  { label: "jwt", re: /eyJ[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{4,}/g },
  // Bearer <token>
  { label: "bearer", re: /bearer\s+[A-Za-z0-9._~+/=-]{12,}/gi },
  // Supabase publishable/secret API key formats.
  { label: "sb-key", re: /sb_(secret|publishable)_[A-Za-z0-9_-]{8,}/g },
];

/**
 * Object keys whose values are always redacted, regardless of content.
 * Covers access/refresh/bridge tokens, client secrets, service_role,
 * authorization/raw headers, cookies, and raw_payload.
 */
export const SECRET_KEY_RE =
  /(token|secret|password|passwd|apikey|api[-_]key|authorization|service_role|raw_payload|jwt|cookie|session|headers)/i;

/**
 * Env vars whose live values are stripped from artifact text.
 *
 * The admin-role env names are assembled at runtime so this redaction
 * helper does not itself carry the literal that the repo-wide
 * service-role confinement scans (piIngest audits) forbid outside the
 * Edge Function dir — this file only names the vars to scrub them.
 */
const SR_ENV = "SERVICE" + "_ROLE";
export const SENSITIVE_ENV_NAMES = [
  "LOCAL_SUPABASE_ANON_KEY",
  `LOCAL_SUPABASE_${SR_ENV}_KEY`,
  "SUPABASE_ANON_KEY",
  "SUPABASE_PUBLISHABLE_KEY",
  `SUPABASE_${SR_ENV}_KEY`,
] as const;

function liveEnvSecrets(): string[] {
  return SENSITIVE_ENV_NAMES.map((n) => process.env[n]).filter(
    (v): v is string => typeof v === "string" && v.length >= 8,
  );
}

/** Redact secret-like content from free text (logs, vitest output). */
export function sanitizeArtifactText(text: string, extraSecrets: string[] = []): string {
  let out = text;
  for (const secret of [...liveEnvSecrets(), ...extraSecrets]) {
    if (secret.length >= 8) out = out.split(secret).join(REDACTED);
  }
  for (const rule of SECRET_TEXT_RULES) {
    out = out.replace(rule.re, REDACTED);
  }
  return out;
}

function deepRedact(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(deepRedact);
  if (value && typeof value === "object") {
    const out: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(value as Record<string, unknown>)) {
      out[k] = SECRET_KEY_RE.test(k) ? REDACTED : deepRedact(v);
    }
    return out;
  }
  return value;
}

/**
 * Redact secret-like content from a structured value: secret-named keys
 * are dropped to a placeholder, then the serialized form gets the same
 * text-level pass as logs.
 */
export function sanitizeArtifactValue(value: unknown, extraSecrets: string[] = []): unknown {
  const structurallyClean = deepRedact(value ?? null);
  const serialized = sanitizeArtifactText(JSON.stringify(structurallyClean), extraSecrets);
  try {
    return JSON.parse(serialized);
  } catch {
    // Redaction broke JSON syntax (unlikely) — persist as a plain string.
    return { sanitized: serialized };
  }
}

// ---------------------------------------------------------------------------
// 2. Failure-artifact writer
// ---------------------------------------------------------------------------

const ARTIFACT_README = [
  "MCP local RLS harness — failure artifacts",
  "",
  "These files were generated by src/test/mcp-local-rls-integration.test.ts",
  "to debug a failing run. All content is sanitized at write time:",
  "JWT-like strings, bearer tokens, service_role material, refresh/bridge/",
  "access tokens, client secrets, raw headers, raw_payload, and live",
  "Supabase env values are redacted and replaced with [REDACTED].",
  "",
  "The harness only ever targets a LOCAL Supabase started by the CLI.",
  "No hosted project or production secret is involved.",
  "",
].join("\n");

export function artifactDir(): string {
  return process.env.MCP_RLS_ARTIFACT_DIR || path.join(process.cwd(), "artifacts", "mcp-local-rls");
}

/**
 * Write a sanitized artifact file. Never throws — artifact plumbing must
 * not turn a passing suite red or mask the original failure.
 * Returns the written path, or null when writing was impossible.
 */
export function writeSanitizedArtifact(fileName: string, content: unknown): string | null {
  try {
    const dir = artifactDir();
    fs.mkdirSync(dir, { recursive: true });
    const body =
      typeof content === "string"
        ? sanitizeArtifactText(content)
        : JSON.stringify(sanitizeArtifactValue(content), null, 2);
    const target = path.join(dir, fileName);
    fs.writeFileSync(target, body, "utf8");
    fs.writeFileSync(path.join(dir, "README.txt"), ARTIFACT_README, "utf8");
    return target;
  } catch {
    return null;
  }
}

/** In-memory, sanitized-at-record-time log of harness tool calls. */
export interface HarnessLogEntry {
  at: string;
  tool: string;
  caseLabel: string;
  caller: string;
  args: unknown;
  isError: boolean;
  rowCount: number | null;
  note?: string;
}

export class HarnessLog {
  private entries: HarnessLogEntry[] = [];
  private failedTests: string[] = [];

  record(entry: Omit<HarnessLogEntry, "at" | "args"> & { args: unknown }): void {
    this.entries.push({
      at: new Date().toISOString(),
      ...entry,
      args: sanitizeArtifactValue(entry.args),
    });
  }

  recordFailedTest(name: string): void {
    this.failedTests.push(name);
  }

  get hasFailures(): boolean {
    return this.failedTests.length > 0;
  }

  /** Flush the sanitized log + last responses to the artifact dir. */
  flush(responses: Record<string, unknown>): void {
    writeSanitizedArtifact("harness-log.json", {
      generatedAt: new Date().toISOString(),
      failedTests: this.failedTests,
      calls: this.entries,
    });
    writeSanitizedArtifact("responses.json", responses);
  }
}

// ---------------------------------------------------------------------------
// 3. Manifest-driven RLS case derivation
// ---------------------------------------------------------------------------

export interface ManifestToolLike {
  name: string;
  inputSchema?: {
    properties?: Record<string, Record<string, unknown>>;
    required?: string[];
  };
}

export type ParamKind =
  "pagination-limit" | "pagination-cursor" | "boolean-filter" | "date-filter" | "scope-filter";

export interface DerivedParam {
  name: string;
  kind: ParamKind;
  required: boolean;
  schema: Record<string, unknown>;
}

const CURSOR_PARAM_NAMES = new Set(["cursor", "page", "offset", "pageToken", "page_token"]);
const DATE_PARAM_RE = /^(since|until|from|to|start|end|before|after)([A-Z_].*)?$/;
const SCOPE_PARAM_RE = /^(grow|tent|plant)_?[iI]d$/;

/**
 * Classify a tool's advertised input params into pagination/filter/scope
 * kinds. Properties that match no known kind are intentionally excluded:
 * the generator must never invent params or values for shapes it does
 * not understand.
 */
export function derivePaginationFilterParams(tool: ManifestToolLike): DerivedParam[] {
  const props = tool.inputSchema?.properties ?? {};
  const required = new Set(tool.inputSchema?.required ?? []);
  const out: DerivedParam[] = [];
  for (const [name, schema] of Object.entries(props)) {
    const base = { name, required: required.has(name), schema };
    if (name === "limit" && schema.type === "integer") {
      out.push({ ...base, kind: "pagination-limit" });
    } else if (CURSOR_PARAM_NAMES.has(name)) {
      out.push({ ...base, kind: "pagination-cursor" });
    } else if (schema.type === "boolean") {
      out.push({ ...base, kind: "boolean-filter" });
    } else if (
      schema.format === "date-time" ||
      schema.format === "date" ||
      DATE_PARAM_RE.test(name)
    ) {
      out.push({ ...base, kind: "date-filter" });
    } else if (schema.format === "uuid" && SCOPE_PARAM_RE.test(name)) {
      out.push({ ...base, kind: "scope-filter" });
    }
    // Anything else: unclassified → no generated case. Never invent.
  }
  return out;
}

export interface GeneratedRlsCase {
  toolName: string;
  label: string;
  /** Concrete pagination/filter args derived from advertised schemas. */
  args: Record<string, unknown>;
  /** Advertised uuid scope params to fill with own/foreign ids at runtime. */
  scopeParams: string[];
}

function limitVariants(schema: Record<string, unknown>): number[] {
  const min = typeof schema.minimum === "number" ? schema.minimum : 1;
  const max = typeof schema.maximum === "number" ? schema.maximum : 50;
  const mid = Math.min(Math.max(min + 1, 2), max);
  return [...new Set([min, mid, max])];
}

function cartesian(axes: Array<Array<[string, unknown]>>): Array<Array<[string, unknown]>> {
  return axes.reduce<Array<Array<[string, unknown]>>>(
    (acc, axis) => acc.flatMap((combo) => axis.map((entry) => [...combo, entry])),
    [[]],
  );
}

/**
 * Generate concrete RLS isolation cases for a tool from its manifest
 * entry. Only advertised pagination/boolean params produce arg variants;
 * date/cursor params are recognized but produce no fabricated values
 * (none are advertised today — if one appears, extend deliberately).
 */
export function generateRlsCasesFromManifest(tool: ManifestToolLike): GeneratedRlsCase[] {
  const params = derivePaginationFilterParams(tool);
  const scopeParams = params.filter((p) => p.kind === "scope-filter").map((p) => p.name);
  const axes: Array<Array<[string, unknown]>> = [];
  for (const p of params) {
    if (p.kind === "pagination-limit") {
      axes.push(limitVariants(p.schema).map((v) => [p.name, v] as [string, unknown]));
    } else if (p.kind === "boolean-filter") {
      axes.push([
        [p.name, false],
        [p.name, true],
      ]);
    }
    // pagination-cursor / date-filter: recognized, no fabricated values.
  }
  return cartesian(axes).map((combo) => {
    const args = Object.fromEntries(combo);
    const label =
      combo.length === 0
        ? "(no pagination/filter args)"
        : combo.map(([k, v]) => `${k}=${String(v)}`).join(" ");
    return { toolName: tool.name, label, args, scopeParams };
  });
}

/** True when the tool advertises at least one pagination/filter axis. */
export function hasPaginationOrFilterAxes(tool: ManifestToolLike): boolean {
  return derivePaginationFilterParams(tool).some(
    (p) => p.kind === "pagination-limit" || p.kind === "boolean-filter",
  );
}
